---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Puoi utilizzare un agente Console per connettere NetApp Console alla tua infrastruttura e orchestrare in modo sicuro le soluzioni di storage su AWS, Azure, Google Cloud o ambienti on-premise, nonché utilizzare i servizi di protezione dei dati. 
---
= Scopri di più sugli agenti NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi utilizzare un agente Console per connettere NetApp Console alla tua infrastruttura e orchestrare in modo sicuro le soluzioni di storage su AWS, Azure, Google Cloud o ambienti on-premise, nonché utilizzare servizi di protezione dei dati.

Un agente Console consente di:

* Orchestra le attività di gestione dello storage dalla NetApp Console, come il provisioning Cloud Volumes ONTAP, la configurazione dei volumi di storage, l'utilizzo della classificazione dei dati e altro ancora.
* Autenticazione tramite i ruoli IAM del tuo provider cloud per l'integrazione della fatturazione degli abbonamenti
* Utilizzare servizi dati avanzati (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience e NetApp Cloud Tiering)


Se non hai bisogno di servizi avanzati di orchestrazione o protezione dei dati, puoi gestire centralmente i cluster ONTAP on-premises e i servizi di cloud-native storage senza dover implementare un agente. Alcuni strumenti di monitoraggio e mobilità dei dati sono disponibili anche senza agente.

Nella tabella seguente vengono mostrate le funzionalità e i servizi che è possibile utilizzare con e senza un agente Console.

[cols="40,20a,20a"]
|===
|  | Disponibile con agente | Disponibile senza agente 


3+| *Sistemi di archiviazione supportati*: 


| Amazon FSx per ONTAP  a| 
Sì (funzionalità di scoperta e gestione)
 a| 
Sì (solo scoperta)



| Archiviazione Amazon S3  a| 
SÌ
 a| 
NO



| Archiviazione BLOB di Azure  a| 
SÌ
 a| 
SÌ



| Azure NetApp Files  a| 
SÌ
 a| 
SÌ



| Cloud Volumes ONTAP  a| 
SÌ
 a| 
NO



| Sistemi della serie E  a| 
SÌ
 a| 
NO



| Google Cloud NetApp Volumes  a| 
SÌ
 a| 
SÌ



| Bucket di archiviazione di Google Cloud  a| 
SÌ
 a| 
NO



| Sistemi StorageGRID  a| 
SÌ
 a| 
NO



| Cluster ONTAP on-premise (gestione e individuazione avanzate)  a| 
Sì (gestione avanzata e scoperta)
 a| 
No (solo scoperta di base)



3+| *Gestione dello storage e servizi di integrità*: 


| Avvisi  a| 
SÌ
 a| 
NO



| Hub di automazione  a| 
SÌ
 a| 
SÌ



| Digital Advisor (Active IQ)  a| 
SÌ
 a| 
NO



| Gestione delle licenze e degli abbonamenti  a| 
SÌ
 a| 
NO



| Efficienza economica  a| 
SÌ
 a| 
NO



| Metriche della dashboard della home page  a| 
Sì^2^
 a| 
NO



| Pianificazione del ciclo di vita  a| 
SÌ
 a| 
No^1^



| Sostenibilità  a| 
SÌ
 a| 
NO



| Aggiornamenti software  a| 
SÌ
 a| 
SÌ



| Carichi di lavoro NetApp  a| 
SÌ
 a| 
SÌ



3+| *Servizi dati disponibili*: 


| NetApp Backup and Recovery  a| 
SÌ
 a| 
NO



| NetApp Data Classification  a| 
SÌ
 a| 
NO



| NetApp Cloud Tiering  a| 
SÌ
 a| 
NO



| NetApp Copy and Sync  a| 
SÌ
 a| 
NO



| NetApp Disaster Recovery  a| 
SÌ
 a| 
NO



| NetApp Ransomware Resilience  a| 
SÌ
 a| 
NO



| NetApp Volume Caching  a| 
SÌ
 a| 
NO

|===
^1^ È possibile visualizzare la pianificazione del ciclo di vita senza un agente della console, ma è necessario un agente della console per avviare le azioni.

^2^ Per ottenere metriche precise nella home page sono necessari agenti della console opportunamente dimensionati e configurati.



== Gli agenti della console devono essere operativi in ogni momento

Gli agenti della console sono una parte fondamentale della NetApp Console.  È tua responsabilità (in quanto cliente) assicurarti che gli agenti competenti siano sempre attivi, operativi e raggiungibili.  La console è in grado di gestire brevi interruzioni dell'agente, ma è necessario risolvere rapidamente i guasti dell'infrastruttura.

La presente documentazione è regolata dall'EULA.  L'utilizzo del prodotto al di fuori della documentazione potrebbe influire sulla sua funzionalità e sui diritti EULA.



== Posizioni supportate

È possibile installare gli agenti nelle seguenti posizioni:

* Servizi Web Amazon
* Microsoft Azure
+
Distribuisci un agente Console in Azure nella stessa area geografica dei sistemi Cloud Volumes ONTAP che gestisce.  In alternativa, distribuiscilo nel https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Coppia di regioni di Azure"^] .  Ciò garantisce che venga utilizzata una connessione Azure Private Link tra Cloud Volumes ONTAP e i relativi account di archiviazione associati. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Scopri come Cloud Volumes ONTAP utilizza un collegamento privato di Azure"^]

* Google Cloud
+
Per utilizzare la Console e i servizi dati con Google Cloud, distribuisci il tuo agente in Google Cloud.

* Presso la vostra sede




== Comunicazione con i provider cloud

L'agente utilizza TLS 1.3 per tutte le comunicazioni con AWS, Azure e Google Cloud.



== Come installare un agente Console

È possibile installare un agente Console direttamente dalla Console, dal marketplace del proprio provider cloud oppure installando manualmente il software sul proprio host Linux o nel proprio ambiente VCenter.

* link:concept-modes.html["Scopri di più sulle modalità di distribuzione NetApp Console"]
* link:task-quick-start-standard-mode.html["Inizia a usare NetApp Console in modalità standard"]
* link:task-quick-start-restricted-mode.html["Inizia a usare NetApp Console in modalità limitata"]




== Autorizzazioni del provider cloud

Sono necessarie autorizzazioni specifiche per creare l'agente Console direttamente dalla NetApp Console e un altro set di autorizzazioni per l'agente Console stesso. Se si crea l'agente Console in AWS o Azure direttamente dalla Console, la Console crea l'agente Console con le autorizzazioni necessarie.

Quando si utilizza la Console in modalità standard, il modo in cui si forniscono le autorizzazioni dipende da come si intende creare l'agente della Console.

Per informazioni su come impostare le autorizzazioni, fare riferimento a quanto segue:

* Modalità standard
+
** link:concept-install-options-aws.html["Opzioni di installazione dell'agente in AWS"]
** link:concept-install-options-azure.html["Opzioni di installazione dell'agente in Azure"]
** link:concept-install-options-google.html["Opzioni di installazione dell'agente in Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Impostare le autorizzazioni cloud per le distribuzioni on-premise"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Imposta le autorizzazioni per la modalità limitata"]


Per visualizzare le autorizzazioni esatte di cui l'agente della console ha bisogno per le operazioni quotidiane, fare riferimento alle seguenti pagine:

* link:reference-permissions-aws.html["Scopri come l'agente della console utilizza le autorizzazioni AWS"]
* link:reference-permissions-azure.html["Scopri come l'agente Console utilizza le autorizzazioni di Azure"]
* link:reference-permissions-gcp.html["Scopri come l'agente della console utilizza le autorizzazioni di Google Cloud"]


È tua responsabilità aggiornare i criteri dell'agente della console man mano che vengono aggiunte nuove autorizzazioni nelle versioni successive.  Le note di rilascio elencano le nuove autorizzazioni.



== Aggiornamenti degli agenti

NetApp aggiorna mensilmente il software dell'agente per aggiungere funzionalità e migliorare la stabilità.  Alcune funzionalità della console, come Cloud Volumes ONTAP e la gestione dei cluster ONTAP in locale, dipendono dalla versione e dalle impostazioni dell'agente della console.

Quando installi l'agente nel cloud, l'agente della console si aggiorna automaticamente se ha accesso a Internet.



== Manutenzione del sistema operativo e della VM

La manutenzione del sistema operativo sull'host dell'agente della console è responsabilità del cliente.  Ad esempio, il cliente dovrebbe applicare gli aggiornamenti di sicurezza al sistema operativo sull'host dell'agente Console seguendo le procedure standard della propria azienda per la distribuzione del sistema operativo.

Tieni presente che non è necessario che tu (cliente) interrompa alcun servizio sull'host Console gent quando applichi aggiornamenti di sicurezza minori.

Se tu (il cliente) hai bisogno di arrestare e poi riavviare la VM dell'agente della console, dovresti farlo dalla console del tuo provider cloud o utilizzando le procedure standard per la gestione in locale.

<<agents-must-be-operational-at-all-times,L'agente della console deve essere operativo in ogni momento>> .



== Sistemi e agenti multipli

Un agente può gestire più sistemi e supportare i servizi dati nella Console.  È possibile utilizzare un singolo agente per gestire più sistemi in base alle dimensioni della distribuzione e ai servizi dati utilizzati.

Per distribuzioni su larga scala, collabora con il tuo rappresentante NetApp per dimensionare il tuo ambiente.  In caso di problemi, contattare l'assistenza NetApp .

Ecco alcuni esempi di distribuzioni di agenti:

* Hai un ambiente multicloud (ad esempio, AWS e Azure) e preferisci avere un agente in AWS e un altro in Azure.  Ognuno gestisce i sistemi Cloud Volumes ONTAP in esecuzione in tali ambienti.
* Un fornitore di servizi potrebbe utilizzare un'organizzazione Console per fornire servizi ai propri clienti e un'altra organizzazione per fornire il ripristino di emergenza per una delle proprie unità aziendali.  Ogni organizzazione ha bisogno del proprio agente.

