---
sidebar: sidebar 
permalink: reference-ports-azure.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: 'Il gruppo di sicurezza di Azure per l"agente richiede sia regole inbound che outbound. La NetApp Console crea automaticamente questo gruppo di sicurezza quando si crea un agente dalla Console. Per altre opzioni di installazione, è necessario configurare manualmente questo gruppo di sicurezza.' 
---
= NetApp Console regole del gruppo di sicurezza dell'agente in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il gruppo di sicurezza di Azure per l'agente richiede sia regole inbound che outbound. La NetApp Console crea automaticamente questo gruppo di sicurezza quando si crea un agente dalla Console. Per altre opzioni di installazione, è necessario configurare manualmente questo gruppo di sicurezza.



[[inbound-rules]]
== Regole in entrata

[cols="3*"]
|===
| Protocollo | Porta | Scopo 


| SSH | 22 | Fornisce accesso SSH all'host dell'agente 


| HTTP | 80  a| 
* Fornisce l'accesso HTTP dai browser Web client all'interfaccia utente locale
* Utilizzato durante il processo di aggiornamento Cloud Volumes ONTAP




| HTTPS | 443 | Fornisce l'accesso HTTPS dai browser Web client all'interfaccia utente locale e connessioni dall'istanza NetApp Data Classification 


| TCP | 3128 | Fornisce a Cloud Volumes ONTAP l'accesso a Internet per inviare messaggi AutoSupport al supporto NetApp .  Dopo la distribuzione, è necessario aprire manualmente questa porta. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-verify-autosupport.html["Scopri come l'agente viene utilizzato come proxy per i messaggi AutoSupport"^] 
|===


[[outbound-rules]]
== Regole in uscita

Il gruppo di sicurezza predefinito per l'agente apre tutto il traffico in uscita.  Se ciò è accettabile, seguite le regole di base per le comunicazioni in uscita.  Se hai bisogno di regole più rigide, usa le regole in uscita avanzate.



[[basic-outbound-rules]]
=== Regole di base in uscita

Il gruppo di sicurezza predefinito per l'agente include le seguenti regole in uscita.

[cols="3*"]
|===
| Protocollo | Porta | Scopo 


| Tutto TCP | Tutto | Tutto il traffico in uscita 


| Tutti gli UDP | Tutto | Tutto il traffico in uscita 
|===


[[advanced-outbound-rules]]
=== Regole in uscita avanzate

Se sono necessarie regole rigide per il traffico in uscita, è possibile utilizzare le seguenti informazioni per aprire solo le porte necessarie per la comunicazione in uscita da parte dell'agente.


NOTE: L'indirizzo IP di origine è l'host dell'agente.

[cols="5*"]
|===
| Servizio | Protocollo | Porta | Destinazione | Scopo 


| Chiamate API e AutoSupport | HTTPS | 443 | Gestione cluster ONTAP e Internet in uscita LIF | Chiamate API ad Azure, a ONTAP, a NetApp Data Classification e invio di messaggi AutoSupport a NetApp 


| chiamate API | TCP | 8080 | Classificazione dei dati | Sonda per l'istanza di classificazione dei dati durante la distribuzione 


| DNS | UDP | 53 | DNS | Utilizzato per la risoluzione DNS dalla Console 
|===