---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: È necessario assicurarsi che la Console e tutti gli agenti installati dispongano del giusto accesso alla rete per funzionare correttamente. 
---
= Accesso di rete richiesto per 3.9.55 e versioni precedenti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, l'agente NetApp Console e i servizi dati NetApp necessitano di accesso a Internet in uscita per contattare gli endpoint necessari.


NOTE: In questo argomento viene documentato l'accesso alla rete richiesto per le versioni della modalità standard 3.9.55 e precedenti della NetApp Console .  Per gli endpoint richiesti per 4.0.0 e versioni successive, rivederelink:reference-networking-saas-console.html["gli endpoint richiesti per 4.0.0 e versioni successive"] .

È necessario configurare l'accesso alla rete per quanto segue:

* Computer che accedono alla NetApp Console come software come servizio (SaaS)
* Agenti console installabili in locale o nel cloud.




== Aggiorna l'elenco degli endpoint all'elenco rivisto per la versione 4.0.0 e successive

A partire dalla versione 4.0.0, gli agenti della console richiedono meno endpoint.  Le distribuzioni esistenti precedenti alla versione 4.0.0 continuano a essere supportate.  Dopo aver effettuato l'aggiornamento alla versione 4.0.0 o successiva, puoi rimuovere i vecchi endpoint dall'elenco consentito quando preferisci.

NetApp consiglia di aggiornare le regole del firewall per utilizzare l'elenco degli endpoint rivisto, che è più piccolo, più sicuro e più facile da gestire.  NetApp elimina la necessità di voci jolly e gli endpoint per gli aggiornamenti degli agenti supportano tutti i servizi dati.

[cols="3*"]
|===
| *Endpoint precedenti* | *Endpoint per 4.0.0 e versioni successive* | *Scopo* 


 a| 
* \ https://support.netapp.com
* \ https://mysupport.netapp.com

 a| 
* \ https://mysupport.netapp.com
* \ https://signin.b2c.netapp.com
* \ https://support.netapp.com

 a| 
Per ottenere le licenze e contattare l'assistenza NetApp .



 a| 
* \https://*.api.bluexp.netapp.com
* \ https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \ https://cloudmanager.cloud.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.bluexp.netapp.com
* \https://*.console.bluexp.netapp.com

 a| 
* \ https://api.bluexp.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \ https://components.console.bluexp.netapp.com
* \ https://cdn.auth0.com

 a| 
Per le operazioni quotidiane.



 a| 
* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io

 a| 
* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io

| Per ottenere immagini per gli aggiornamenti dell'agente della console. 
|===
.Passi
. Verifica che la versione dell'agente sia 4.0.0 o successiva.link:task-troubleshoot-agent.html#view-the-console-agent-version["Visualizza la versione dell'agente."]
. Aggiungi alla whitelist gli endpoint inlink:reference-networking-saas-console.html["Endpoint supportati per 4.0.0 e versioni successive"] .
. Riavviare il servizio Service Manager 2 su ciascun agente eseguendo il seguente comando:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Eseguire il seguente comando e verificare che lo stato dell'agente sia _attivo(in esecuzione)_: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. Rimuovi i vecchi endpoint dall'elenco consentito del firewall.




== Endpoint per NetApp Console e agenti Console per 3.9.55 e versioni precedenti

Questi endpoint vengono utilizzati per gli agenti Console 3.9.55 e versioni precedenti.

[cols="2*"]
|===
| Punti finali | Scopo 


 a| 
\ https://support.netapp.com \ https://mysupport.netapp.com
 a| 
Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp .



 a| 
\https://\*.api.blueexp.netapp.com \ https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \ https://cloudmanager.cloud.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com
| Per fornire funzionalità e servizi all'interno della NetApp Console. 


 a| 
Scegli tra due serie di endpoint:

* Opzione 1 (consigliata)
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* Opzione 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


 a| 
Per ottenere immagini per gli aggiornamenti dell'agente della console.

NetApp consiglia di consentire gli endpoint dell'Opzione 1 nel firewall in quanto più sicuri e di non consentire gli endpoint dell'Opzione 2, a meno che non si utilizzi Ransomware Resilience o Backup and Recovery.  Si tenga presente quanto segue in merito a questi endpoint:

* Gli endpoint dell'opzione 1 sono supportati nella versione 3.9.47 e successive.  Le versioni precedenti alla 3.9.47 non supportano la compatibilità con le versioni precedenti.
* L'agente della console avvia prima il contatto con gli endpoint nell'opzione 2.  Se tali endpoint non sono accessibili, vengono contattati automaticamente gli endpoint nell'opzione 1.
* Se si utilizza l'agente Console con NetApp Backup and Recovery o Ransomware Resilience, il sistema non supporta gli endpoint Opzione 1.  Consentire gli endpoint dell'opzione 2 e non consentire l'opzione 1.


|===


== Endpoint del provider cloud contattati dall'agente della console

Gli agenti della console devono avere accesso ad endpoint aggiuntivi se sono distribuiti nel tuo provider cloud.

Abilitare l'accesso agli endpoint del provider cloud prima di installare l'agente Console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurare l'accesso alla rete AWS per un agente della console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurare l'accesso alla rete di Azure per un agente della console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurare l'accesso alla rete Google Cloud per un agente della console"]


Gli endpoint del provider cloud sono gli stessi per tutte le versioni.



== Endpoint dei servizi dati contattati dall'agente della console

L'agente Console richiede un accesso Internet in uscita aggiuntivo per supportare alcuni servizi dati NetApp e Cloud Volumes ONTAP.



=== Endpoint per Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpoint per Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Endpoint per Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Endpoint per Cloud Volumes ONTAP in Google Cloud"]

