---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: 'È possibile utilizzare la console di manutenzione dell"agente Console per convalidare l"installazione e la configurazione di un agente Console.' 
---
= Convalida dell'agente della console con la console di manutenzione in NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare la console di manutenzione dell'agente Console per convalidare l'installazione e la configurazione di un agente Console.



[[access-the-agent-maintenance-console]]
== Accedi alla console di manutenzione dell'agente

È possibile accedere alla console di manutenzione dall'host dell'agente della console. Accedere alla seguente directory:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


[[config-checker-validate]]
== verifica della configurazione convalida

IL `config-checker validate` Il comando consente di convalidare la configurazione di un agente Console.

link:reference-networking-saas-console.html["Scopri di più sui punti di accesso alla rete richiesti."] link:task-install-agent-on-prem.html#os-req-agent["Scopri di più sui requisiti dell'host."]



[[parameters]]
=== Parametri

`--services <comma-separated list of services to validate>`--*NECESSARIO*--

[role="quick-margin-para"]
Seleziona uno o più servizi da convalidare. I nomi dei servizi validi sono:

* `PLATFORM`che convalida la connettività di rete agli endpoint della Console richiesti, nonché se le porte necessarie sono aperte per l'agente della Console.


`--validationTypes <comma-separated list of validation types to run>` --*OBBLIGATORIO*-- Scegli uno o più tipi di convalida da eseguire. I tipi di convalida validi sono:

* `NETWORK`che convalida la connettività di rete agli endpoint Console richiesti.
* `HARDWARE`che convalida che l'host dell'agente soddisfa i requisiti hardware minimi per l'agente della Console.
+

NOTE: Durante l'installazione, NetApp verifica che l'host dell'agente disponga di almeno l'80% dello spazio su disco totale disponibile, che include 48 GB in `/opt` e 32 GB in `/var` (80 GB totali). Dopo l'installazione, è necessario che rimanga disponibile almeno il 20% dello spazio su disco totale, che include 12 GB in `/opt` e 8 GB in `/var` (20 GB totali).



`--proxy <url>`--*OPZIONALE*--

[role="quick-margin-para"]
Specifica l'URL del server proxy da utilizzare per la convalida.  Obbligatorio se l'agente è configurato per utilizzare un server proxy.

`--certs <paths>`--*OPZIONALE*--

[role="quick-margin-para"]
Specifica il percorso di uno o più file di certificato da utilizzare per la convalida.  I file del certificato devono essere in formato PEM.  Separare i percorsi multipli con virgole.  Questo parametro è obbligatorio se l'agente utilizza un certificato personalizzato.



[[config-checker-validate-examples]]
=== Esempi di convalida del controllo di configurazione

Gli esempi seguenti includono la convalida della connettività di rete, delle porte richieste e dei requisiti hardware, insieme a diverse combinazioni di utilizzo di un proxy server e certificati personalizzati.

.Validazione della connettività di rete e dei requisiti hardware:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.Convalida in cui viene utilizzato un server proxy per l'agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.Convalida in cui viene utilizzato un certificato per l'agente:
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


[[view-help-for-any-command]]
=== Visualizza la guida per qualsiasi comando

Per visualizzare la guida per qualsiasi comando, aggiungi `--help` al comando.  Ad esempio, per visualizzare la guida per `proxy add` comando, utilizzare il seguente comando:

[source, cli]
----
./agent-maint-console proxy add --help
----