---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: 'NetApp Console, l"agente NetApp Console e i servizi dati NetApp richiedono l"accesso a Internet in uscita e la possibilità di contattare gli endpoint necessari.' 
---
= Accesso alla rete per NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, l'agente NetApp Console e i servizi dati NetApp richiedono l'accesso a Internet in uscita e la possibilità di contattare gli endpoint necessari.

Sarà necessario configurare l'accesso alla rete per quanto segue:

* Computer che accedono alla NetApp Console come software come servizio (SaaS)
* Agenti console installabili in locale o nel cloud. Agenti della console.



NOTE: Con la versione 4.0.0, NetApp ha ridotto gli endpoint di rete richiesti per la Console e gli agenti della Console, migliorando la sicurezza e semplificando la distribuzione. È importante sottolineare che tutte le distribuzioni precedenti alla versione 4.0.0 continuano a essere pienamente supportate.  Sebbene gli endpoint precedenti rimangano disponibili per gli agenti esistenti, NetApp consiglia vivamente di aggiornare le regole del firewall agli endpoint correnti dopo aver confermato il corretto aggiornamento degli agenti.link:reference-networking-saas-console-previous.html["Scopri come aggiornare l'elenco degli endpoint."]



== Endpoint contattati da NetApp Console e dagli agenti della console

Ogni agente distribuito e ogni computer che accede alla NetApp Console devono disporre di connessioni agli endpoint elencati di seguito.

Gli agenti della console distribuiti nel tuo provider cloud necessitano di accedere agli endpoint rispettivi di quel provider cloud.

[cols="2*"]
|===
| Punti finali | Scopo 


| \ https://mysupport.netapp.com | Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp . 


| \ https://signin.b2c.netapp.com | Per aggiornare le credenziali del sito di supporto NetApp (NSS) o per aggiungere nuove credenziali NSS alla NetApp Console. 


| \ https://support.netapp.com | Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp , nonché per ricevere aggiornamenti software per Cloud Volumes ONTAP. 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com | Per fornire funzionalità e servizi all'interno della NetApp Console. 


 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Per ottenere immagini per gli aggiornamenti dell'agente della console.

* Quando si distribuisce un nuovo agente, il controllo di convalida verifica la connettività agli endpoint correnti. Se usilink:reference-networking-saas-console-previous.html["punti finali precedenti"] , il controllo di convalida fallisce. Per evitare questo errore, saltare il controllo di convalida.
+
Sebbene gli endpoint precedenti siano ancora supportati, NetApp consiglia di aggiornare le regole del firewall agli endpoint correnti il ​​prima possibile. link:reference-networking-saas-console-previous.html#update-endpoint-list["Scopri come aggiornare l'elenco degli endpoint"] .

* Quando esegui l'aggiornamento agli endpoint correnti nel firewall, gli agenti esistenti continueranno a funzionare.




 a| 
\https://occmclientinfragov.azurecr.us.io \https://bluexpinfraprod.azurecr.io
 a| 
Per ottenere immagini per gli aggiornamenti dell'agente della console.

* Quando si distribuisce un nuovo agente, il controllo di convalida verifica la connettività agli endpoint correnti. Se usilink:reference-networking-saas-console-previous.html["punti finali precedenti"] , il controllo di convalida fallisce. Per evitare questo errore, saltare il controllo di convalida.
+
Sebbene gli endpoint precedenti siano ancora supportati, NetApp consiglia di aggiornare le regole del firewall agli endpoint correnti il ​​prima possibile. link:reference-networking-saas-console-previous.html#update-endpoint-list["Scopri come aggiornare l'elenco degli endpoint"] .

* Quando esegui l'aggiornamento agli endpoint correnti nel firewall, gli agenti esistenti continueranno a funzionare.


^1^ NetApp consiglia di consentire gli endpoint dell'Opzione 1 nel firewall in quanto più sicuri e di non consentire gli endpoint dell'Opzione 2.  Si tenga presente quanto segue in merito a questi endpoint:

+ * A partire dalla versione 3.9.47 dell'agente Console, il sistema supporta gli endpoint elencati nell'opzione 1.  Le versioni precedenti dell'agente Console non supportano la compatibilità con le versioni precedenti.  * L'agente della console contatta prima gli endpoint nell'opzione 2.  Se tali endpoint non sono accessibili, vengono contattati automaticamente gli endpoint nell'opzione 1.  * Se si utilizza l'agente Console con NetApp Backup and Recovery o Ransomware Resilience, il sistema non supporta gli endpoint Opzione 1.  Consentire gli endpoint dell'opzione 2 e non consentire l'opzione 1.



| Se l'agente della console si trova in una regione AWS Government: \https://*.blob.core.windows.net https://cloudmanagerinfraprod.azurecr.io | Per ottenere le immagini per gli aggiornamenti dell'agente Console quando quest'ultimo è installato in una regione AWS Government. 


| Se l'agente della console si trova in un'area geografica di Azure Government: \https://*.blob.core.windows.net https://occmclientinfragov.azurecr.us | Per ottenere le immagini per gli aggiornamenti dell'agente Console quando l'agente Console è installato in un'area geografica di Azure Government. 


 a| 
Se l'agente della console si trova in una regione commerciale o in una regione sovrana, è possibile scegliere tra due set di endpoint:

* Opzione 1 (consigliata) ^1^
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* Opzione 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


| Per ottenere le immagini per gli aggiornamenti dell'agente Console quando l'agente Console è installato in una regione commerciale o regione sovrana. [cols=3*,options="header,autowidth"] 
|===
|*Endpoint per 3.9.55 e precedenti* | *Endpoint per 4.0.0 e successive* | *Scopo*

a| * https://support.netapp.com * https://mysupport.netapp.com a| * https://mysupport.netapp.com * https://signin.b2c.netapp.com * https://support.netapp.com a| Per la gestione delle licenze e per contattare il supporto NetApp. a| * https://*.api.bluexp.netapp.com * https://api.bluexp.netapp.com * https://*.cloudmanager.cloud.netapp.com * https://cloudmanager.cloud.netapp.com * https://netapp-cloud-account.auth0.com * https://netapp-cloud-account.us.auth0.com * https://console.netapp.com * https://*.console.netapp.com a| * https://api.bluexp.netapp.com * https://netapp-cloud-account.auth0.com * https://netapp-cloud-account.us.auth0.com * https://console.netapp.com * https://components.console.netapp.com * https://cdn.auth0.com a| Per le operazioni quotidiane. a| * https://*.blob.core.windows.net * https://cloudmanagerinfraprod.azurecr.io a| * https://bluexpinfraprod.eastus2.data.azurecr.io * https://bluexpinfraprod.azurecr.io | Per ottenere immagini per gli aggiornamenti dell'agente Console.

|===
|===


== Gli endpoint del provider cloud hanno contattato l'agente della console

Gli agenti della console devono avere accesso ad endpoint aggiuntivi se sono distribuiti nel tuo provider cloud.

Configurare l'accesso all'endpoint di rete del provider cloud prima di installare l'agente Console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurare l'accesso alla rete AWS per un agente della console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurare l'accesso alla rete di Azure per un agente della console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurare l'accesso alla rete Google Cloud per un agente della console"]




== Endpoint dei servizi dati contattati dall'agente della console

Alcuni servizi dati NetApp e Cloud Volumes ONTAP richiedono che l'agente disponga di un accesso Internet in uscita aggiuntivo.



=== Endpoint per Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpoint per Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Endpoint per Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Endpoint per Cloud Volumes ONTAP in Google Cloud"]




=== Endpoint per carichi di lavoro

L'agente della console deve essere in grado di accedere al seguente endpoint per NetApp Workloads.

[cols="2*"]
|===
| Punti finali | Scopo 


 a| 
\ https://api.workloads.netapp.com
 a| 
La console basata sul Web contatta questo endpoint per interagire con le API di Workload Factory per gestire e utilizzare i carichi di lavoro basati su FSx for ONTAP.

|===