---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions, bluexp, console agent 
summary: 'L"agente della console necessita delle autorizzazioni per eseguire azioni nel tuo provider cloud.  Queste autorizzazioni sono incluse nelle policy fornite da NetApp.  Dovresti capire cosa fa l"agente con queste autorizzazioni.' 
---
= Autorizzazioni di Google Cloud per l'agente della console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'agente della console necessita delle autorizzazioni per eseguire azioni in Google Cloud. Queste autorizzazioni sono incluse in un ruolo personalizzato fornito da NetApp. Dovresti capire cosa fa l'agente con queste autorizzazioni.



== Autorizzazioni dell'account utente di Google Cloud

Il ruolo personalizzato riportato di seguito fornisce a un utente Google Cloud le autorizzazioni necessarie per distribuire un agente.  Applica questo ruolo personalizzato all'utente che distribuirà l'agente.

.Visualizza le autorizzazioni dell'account utente di Google Cloud
[%collapsible]
====
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
====


== Autorizzazioni dell'account di servizio

Il ruolo personalizzato riportato di seguito fornisce all'account del servizio Google Cloud associato all'agente della console le autorizzazioni necessarie per gestire risorse e processi nella rete Google Cloud.

Applica questo ruolo personalizzato a un account di servizio collegato alla VM dell'agente Console.

* link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Imposta le autorizzazioni di Google Cloud per la modalità standard"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Imposta le autorizzazioni per la modalità limitata"]


.Visualizza le autorizzazioni dell'account di servizio Google
[%collapsible]
====
Assicurarsi che il ruolo sia aggiornato poiché nuove autorizzazioni vengono aggiunte o rimosse nelle versioni successive.  Il registro delle modifiche elenca tutte le nuove autorizzazioni richieste.link:reference-permissions-gcp.html#gcp-permissions-change-log["Esamina il registro delle modifiche alle autorizzazioni di Google"] link:task-adding-gcp-accounts.html["Scopri come aggiungere account di servizi Google Cloud"]

[source, yaml]
----
title: NetApp Console agent
description: Permissions for the service account associated with the Console agent.
stage: GA
includedPermissions:
- cloudbuild.builds.get
- cloudbuild.connections.list
- cloudbuild.repositories.accessReadToken
- cloudbuild.repositories.list
- cloudquotas.quotas.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
- config.artifacts.import
- config.deployments.create
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getLock
- config.deployments.getState
- config.deployments.update
- config.deployments.updateState
- config.previews.upload
- config.revisions.get
- config.revisions.getState
- config.deployments.getLock
- config.deployments.list
- config.deployments.lock
- config.operations.get
- config.previews.get
- config.previews.list
- config.resources.list
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.regionBackendServices.update
- compute.networks.updatePolicy
- compute.addresses.createInternal
- compute.addresses.deleteInternal
- compute.addresses.list
- compute.addresses.setLabels
- compute.addresses.useInternal
- compute.backendServices.create
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.forwardingRules.create
- compute.forwardingRules.delete
- compute.forwardingRules.get
- compute.forwardingRules.setLabels
- compute.globalOperations.get
- compute.healthChecks.create
- compute.healthChecks.delete
- compute.healthChecks.get
- compute.healthChecks.useReadOnly
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instances.use
- compute.instanceGroups.create
- compute.instanceGroups.delete
- compute.instanceGroups.get
- compute.instanceGroups.update
- compute.instanceGroups.use
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.instances.setMinCpuPlatform
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.regionBackendServices.delete
- compute.regionBackendServices.use
- compute.resourcePolicies.create
- compute.resourcePolicies.delete
- compute.resourcePolicies.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- logging.logEntries.create
- logging.logEntries.route
- monitoring.timeSeries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- storage.objects.create
- storage.objects.delete
- storage.objects.update
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.objects.get
- storage.buckets.getIamPolicy



----
====


== Come vengono utilizzate le autorizzazioni di Google Cloud

L'agente Console utilizza le autorizzazioni nel ruolo personalizzato per gestire le risorse Cloud Volumes ONTAP e i processi dei servizi dati NetApp nella rete Google Cloud.  Le sezioni seguenti descrivono come l'agente utilizza queste autorizzazioni.



=== Autorizzazioni utilizzate per Cloud Volumes ONTAP

L'agente Console utilizza le autorizzazioni nel ruolo personalizzato per gestire le risorse e i processi Cloud Volumes ONTAP nella rete Google Cloud.  Le sezioni seguenti descrivono come l'agente utilizza queste autorizzazioni.

.Autorizzazioni per Cloud Volumes ONTAP
[%collapsible]
====
[cols="5*"]
|===
| Azioni | Scopo | Utilizzato per la distribuzione? | Utilizzato per le operazioni quotidiane? | Utilizzato per l'eliminazione? 


| config.deployments.create .15+| Per distribuire l'istanza della macchina virtuale Cloud Volumes ONTAP utilizzando Google Cloud Infrastructure Manager. | SÌ | NO | NO 


| config.deployments.delete | NO | NO | SÌ 


| config.deployments.deleteState | NO | NO | SÌ 


| config.deployments.get | NO | SÌ | NO 


| config.deployments.getLock | NO | SÌ | NO 


| config.deployments.getState | NO | SÌ | NO 


| config.deployments.list | NO | SÌ | NO 


| configurazione.distribuzioni.blocco | NO | SÌ | NO 


| config.deployments.update | NO | SÌ | NO 


| config.deployments.updateState | NO | SÌ | NO 


| config.operations.get | NO | SÌ | NO 


| config.previews.get | NO | SÌ | NO 


| config.anteprime.elenco | NO | SÌ | NO 


| elenco risorse di configurazione | NO | SÌ | NO 


| config.revisions.get | NO | SÌ | NO 


| calcola.dischi.crea .7+| Per creare e gestire dischi per Cloud Volumes ONTAP. | SÌ | SÌ | NO 


| calcola.dischi.creaSnapshot | NO | SÌ | NO 


| calcola.dischi.elimina | NO | SÌ | SÌ 


| compute.disks.get | NO | SÌ | NO 


| elenco.dischi.di calcolo | SÌ | SÌ | NO 


| calcola.dischi.imposta etichette | SÌ | SÌ | NO 


| calcolo.dischi.uso | NO | SÌ | NO 


| calcola.firewall.crea .4+| Per creare regole firewall per Cloud Volumes ONTAP. | SÌ | NO | NO 


| calcola.firewall.elimina | NO | SÌ | SÌ 


| calcola.firewall.ottieni | SÌ | SÌ | NO 


| elenco.firewall.di.calcolo | SÌ | SÌ | NO 


| calcola.regolediinoltro.crea | Creare regole di inoltro per l'instradamento del traffico verso i servizi backend. | NO | SÌ | NO 


| calcola.regolediinoltro.elimina | Elimina le regole di inoltro esistenti. | NO | SÌ | NO 


| calcola.regolediinoltro.ottieni | Recupera i dettagli sulle regole di inoltro esistenti. | NO | SÌ | NO 


| calcola.regolediinoltro.impostaetichette | Imposta o aggiorna le etichette sulle regole di inoltro per l'organizzazione. | NO | SÌ | NO 


| compute.globalOperations.get | Per conoscere lo stato delle operazioni. | SÌ | SÌ | NO 


| calcola.controlli.salute.crea .4+| Crea e gestisci controlli di integrità per monitorare lo stato di salute del servizio backend. | NO | SÌ | NO 


| compute.healthChecks.delete | NO | SÌ | NO 


| compute.healthChecks.get | NO | SÌ | NO 


| compute.healthChecks.useReadOnly | NO | SÌ | NO 


| calcola.immagini.ottieni .4+| Per ottenere immagini per istanze VM. | SÌ | NO | NO 


| calcola.immagini.getFromFamily | SÌ | NO | NO 


| calcola.elenco.immagini | SÌ | NO | NO 


| calcola.immagini.usasola lettura | SÌ | NO | NO 


| calcola.istanze.attachDisk .2+| Per collegare e scollegare i dischi a Cloud Volumes ONTAP. | SÌ | SÌ | NO 


| calcola.istanze.staccaDisco | NO | SÌ | SÌ 


| calcola.istanze.crea .2+| Per creare ed eliminare istanze VM Cloud Volumes ONTAP . | SÌ | NO | NO 


| calcola.istanze.elimina | NO | NO | SÌ 


| calcola.istanze.ottieni | Per elencare le istanze VM. | SÌ | SÌ | NO 


| calcola.istanze.getSerialPortOutput | Per ottenere i log della console. | SÌ | SÌ | NO 


| elenco.istanze.di.calcolo | Per recuperare l'elenco delle istanze in una zona. | SÌ | SÌ | NO 


| compute.instances.setDeletionProtection | Per impostare la protezione dall'eliminazione sull'istanza. | SÌ | NO | NO 


| calcola.istanze.imposta etichette | Per aggiungere etichette. | SÌ | NO | NO 


| calcola.istanze.impostatipomacchina .2+| Per modificare il tipo di macchina per Cloud Volumes ONTAP. | SÌ | SÌ | NO 


| calcola.istanze.impostaMinCpuPlatform | SÌ | SÌ | NO 


| calcola.istanze.impostaMetadati | Per aggiungere metadati. | SÌ | SÌ | NO 


| calcola.istanze.impostaTag | Per aggiungere tag per le regole del firewall. | SÌ | SÌ | NO 


| calcola.istanze.avvio .3+| Per avviare e arrestare Cloud Volumes ONTAP. | SÌ | SÌ | NO 


| calcola.istanze.arresto | SÌ | SÌ | NO 


| calcola.istanze.aggiorna.dispositivo di visualizzazione | SÌ | SÌ | NO 


| calcola.istanze.uso | Utilizzare istanze di macchine virtuali (operazioni di avvio, arresto e connessione). | NO | SÌ | NO 


| calcola.tipimacchina.ottieni | Per ottenere il numero di core per controllare le quote. | SÌ | NO | NO 


| calcola.progetti.ottieni | Per supportare progetti multipli. | SÌ | NO | NO 


| calcola.risorsePolitiche.crea .3+| Crea e gestisci policy sulle risorse per la gestione automatizzata delle risorse. | NO | SÌ | NO 


| compute.resourcePolicies.delete | NO | SÌ | NO 


| compute.resourcePolicies.get | NO | SÌ | NO 


| calcola.istantanee.crea .5+| Per creare e gestire snapshot persistenti del disco. | SÌ | SÌ | NO 


| calcola.istantanee.elimina | NO | SÌ | SÌ 


| calcola.istantanee.ottieni | NO | SÌ | NO 


| elenco di istantanee di calcolo | NO | SÌ | NO 


| calcola.istantanee.imposta etichette | SÌ | SÌ | NO 


| compute.networks.get .9+| Per ottenere le informazioni di rete necessarie per creare una nuova istanza di macchina virtuale Cloud Volumes ONTAP . | SÌ | SÌ | NO 


| elenco.reti.di.calcolo | SÌ | SÌ | NO 


| calcola.regioni.ottieni | SÌ | SÌ | NO 


| calcola.elenco.regioni | SÌ | SÌ | NO 


| calcola.sottoreti.ottenere | SÌ | SÌ | NO 


| elenco.sottoreti.di.calcolo | SÌ | SÌ | NO 


| compute.zoneOperations.get | SÌ | SÌ | NO 


| calcola.zone.get | SÌ | SÌ | NO 


| elenco.zone.di.calcolo | SÌ | SÌ | NO 


| deploymentmanager.compositeTypes.get .16+| Per distribuire l'istanza della macchina virtuale Cloud Volumes ONTAP utilizzando Google Cloud Deployment Manager. | SÌ | NO | NO 


| deploymentmanager.compositeTypes.list | SÌ | NO | NO 


| deploymentmanager.deployments.create | SÌ | NO | NO 


| deploymentmanager.deployments.delete | SÌ | NO | NO 


| deploymentmanager.deployments.get | SÌ | NO | NO 


| gestoredistribuzioni.elencodistribuzioni | SÌ | NO | NO 


| deploymentmanager.manifests.get | SÌ | NO | NO 


| deploymentmanager.manifests.list | SÌ | NO | NO 


| deploymentmanager.operations.get | SÌ | NO | NO 


| gestoredistribuzioni.elencooperazioni | SÌ | NO | NO 


| deploymentmanager.resources.get | SÌ | NO | NO 


| elenco risorse del gestore di distribuzione | SÌ | NO | NO 


| deploymentmanager.typeProviders.get | SÌ | NO | NO 


| deploymentmanager.typeProviders.list | SÌ | NO | NO 


| deploymentmanager.types.get | SÌ | NO | NO 


| elenco dei tipi di deploymentmanager | SÌ | NO | NO 


| logging.logEntries.list .2+| Per ottenere unità di registro dello stack. | SÌ | SÌ | NO 


| logging.privateLogEntries.list | SÌ | SÌ | NO 


| registrazione.logEntries.create .2+| Crea e instrada voci di registro per il monitoraggio, il debug e l'audit. | SÌ | SÌ | NO 


| registrazione.logEntries.route | SÌ | SÌ | NO 


| resourcemanager.projects.get | Per supportare progetti multipli. | SÌ | SÌ | NO 


| storage.buckets.create .5+| Per creare e gestire un bucket di Google Cloud Storage per la suddivisione in livelli dei dati. | SÌ | SÌ | NO 


| storage.buckets.delete | NO | SÌ | SÌ 


| storage.buckets.get | NO | SÌ | NO 


| elenco.secchi.di.archiviazione | NO | SÌ | NO 


| aggiornamento.storage.buckets | NO | SÌ | NO 


| cloudkms.cryptoKeyVersions.useToEncrypt .5+| Per utilizzare le chiavi di crittografia gestite dal cliente dal Cloud Key Management Service con Cloud Volumes ONTAP. | SÌ | SÌ | NO 


| cloudkms.cryptoKeys.get | SÌ | SÌ | NO 


| cloudkms.cryptoKeys.list | SÌ | SÌ | NO 


| cloudkms.keyRings.list | SÌ | SÌ | NO 


| cloudbuild.builds.get | SÌ | NO | NO 


| calcola.istanze.impostaAccountServizio .6+| Per impostare un account di servizio sull'istanza Cloud Volumes ONTAP .  Questo account di servizio fornisce le autorizzazioni per il tiering dei dati in un bucket di Google Cloud Storage. | SÌ | SÌ | NO 


| iam.serviceAccounts.actAs | SÌ | NO | NO 


| iam.serviceAccounts.create | SÌ | NO | NO 


| iam.serviceAccounts.getIamPolicy | SÌ | SÌ | NO 


| iam.serviceAccounts.list | SÌ | SÌ | NO 


| iam.serviceAccountKeys.create | SÌ | NO | NO 


| archiviazione.oggetti.crea .4+| Crea e gestisci oggetti (file) nel bucket di Google Cloud Storage. | SÌ | SÌ | NO 


| archiviazione.oggetti.elimina | NO | NO | SÌ 


| storage.objects.get | SÌ | SÌ | NO 


| elenco.oggetti.di.archiviazione | SÌ | SÌ | NO 


| calcola.elenco.indirizzi | Per recuperare gli indirizzi in una regione durante la distribuzione di una coppia HA. | SÌ | NO | NO 


| calcola.indirizzi.crea.interno | Creare indirizzi IP interni all'interno della rete VPC per l'allocazione delle risorse. | NO | SÌ | NO 


| calcola.indirizzi.eliminaInterno | Elimina gli indirizzi IP interni per la pulizia delle risorse. | NO | SÌ | NO 


| calcola.indirizzi.imposta.etichette | Aggiorna le etichette sulla risorsa Indirizzo. | NO | SÌ | NO 


| calcola.indirizzi.usaInterno | Utilizzare indirizzi IP interni per la comunicazione di rete. | NO | SÌ | NO 


| compute.backendServices.create | Per configurare un servizio backend per la distribuzione del traffico in una coppia HA. | SÌ | NO | NO 


| compute.regionBackendServices.create .6+| Crea e gestisci servizi backend per l'instradamento del traffico. | SÌ | NO | NO 


| compute.regionBackendServices.delete | NO | SÌ | NO 


| compute.regionBackendServices.get | SÌ | NO | NO 


| compute.regionBackendServices.update | SÌ | SÌ | NO 


| compute.regionBackendServices.list | SÌ | NO | NO 


| compute.regionBackendServices.use | NO | SÌ | NO 


| compute.networks.updatePolicy | Per applicare regole firewall alle VPC e alle subnet per una coppia HA. | SÌ | NO | NO 


| compute.instanceGroups.get .7+| Per creare e gestire VM di storage su coppie Cloud Volumes ONTAP HA. | SÌ | SÌ | NO 


| calcola.indirizzi.ottieni | SÌ | SÌ | NO 


| calcola.istanze.aggiornaInterfaccia di rete | SÌ | SÌ | NO 


| compute.instanceGroups.create | NO | SÌ | NO 


| compute.instanceGroups.delete | NO | SÌ | NO 


| compute.instanceGroups.update | NO | SÌ | NO 


| compute.instanceGroups.use | NO | SÌ | NO 


| monitoraggio.timeSeries.list .2+| Per scoprire informazioni sui bucket di Google Cloud Storage. | SÌ | SÌ | NO 


| storage.buckets.getIamPolicy | SÌ | SÌ | NO 
|===
====


=== Autorizzazioni utilizzate per NetApp Backup and Recovery

L'agente Console utilizza le autorizzazioni nel ruolo personalizzato per gestire le risorse e i processi NetApp Backup and Recovery nella rete Google Cloud.  Le sezioni seguenti descrivono come l'agente utilizza queste autorizzazioni.

.Visualizza le autorizzazioni per NetApp Backup and Recovery
[%collapsible]
====
[cols="5*"]
|===


| Azioni | Scopo | Utilizzato per la distribuzione? | Utilizzato per le operazioni quotidiane? | Utilizzato per l'eliminazione? 


 a| 
* cloudkms.cryptoKeys.get
* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.list
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.list
* cloudkms.keyRings.setIamPolicy

| Per selezionare le chiavi gestite dal cliente nella procedura guidata di attivazione NetApp Backup and Recovery anziché utilizzare le chiavi di crittografia predefinite gestite da Google. | SÌ | SÌ | NO 
|===
====


=== Autorizzazioni utilizzate per la NetApp Data Classification

L'agente Console utilizza le autorizzazioni nel ruolo personalizzato per gestire le risorse e i processi NetApp Data Classification nella rete Google Cloud.  Le sezioni seguenti descrivono come l'agente utilizza queste autorizzazioni.

.Visualizza le autorizzazioni per la NetApp Data Classification
[%collapsible]
====
[cols="5*"]
|===


| Azioni | Scopo | Utilizzato per la distribuzione? | Utilizzato per le operazioni quotidiane? | Utilizzato per l'eliminazione? 


 a| 
* calcolo.sottoreti.uso
* calcola.sottoreti.usaIPesterno
* calcola.istanze.aggiungiAccessConfig

| Per abilitare la NetApp Data Classification. | SÌ | NO | NO 
|===
====


== Registro delle modifiche

Di seguito sono riportati i permessi aggiunti e rimossi.



=== 08 dicembre 2025

NetApp sta passando da Google Cloud Deployment Manager a Google Cloud Infrastructure Manager (IM) per distribuire ed eseguire l'agente Console in Google Cloud.  Per supportare questa modifica sono state aggiunte le seguenti autorizzazioni.

Per l'utente Google Cloud che distribuisce l'agente sono necessarie le seguenti autorizzazioni aggiuntive:

* storage.buckets.create
* storage.buckets.get
* archiviazione.oggetti.crea
* archiviazione.cartelle.crea
* elenco.oggetti.di.archiviazione
* iam.serviceAccount.actAs
* config.deployments.create
* config.operations.get


Per l'account di servizio in Google Cloud utilizzato per le operazioni quotidiane sono necessarie le seguenti autorizzazioni aggiuntive:

* cloudbuild.connections.list
* cloudbuild.repositories.accessReadToken
* cloudbuild.repositories.list
* cloudquotas.quotas.get
* config.artifacts.import
* config.deployments.deleteState
* config.deployments.getLock
* config.deployments.getState
* config.deployments.updateState
* config.anteprime.carica
* config.revisions.getState
* registrazione.logEntries.create
* archiviazione.oggetti.crea
* archiviazione.oggetti.elimina
* aggiornamento.oggetti.di.archiviazione
* iam.serviceAccounts.get


Per distribuire Cloud Volumes ONTAP sono necessarie le seguenti autorizzazioni aggiuntive:

* cloudbuild.builds.get
* config.deployments.delete
* config.deployments.deleteState
* config.deployments.get
* config.deployments.getState
* config.deployments.list
* config.deployments.update
* config.deployments.updateState
* config.previews.get
* config.anteprime.elenco
* config.revisions.get
* elenco risorse di configurazione
* iam.serviceAccountKeys.create
* iam.serviceAccounts.create


Per l'account di servizio utilizzato per le operazioni quotidiane di Cloud Volumes ONTAP sono necessarie le seguenti autorizzazioni aggiuntive.

* calcola.indirizzi.crea.interno
* calcola.indirizzi.eliminaInterno
* calcola.indirizzi.imposta.etichette
* calcola.indirizzi.usaInterno
* calcola.regolediinoltro.crea
* calcola.regolediinoltro.elimina
* calcola.regolediinoltro.ottieni
* calcola.regolediinoltro.impostaetichette
* calcola.controlli.salute.crea
* compute.healthChecks.delete
* compute.healthChecks.get
* compute.healthChecks.useReadOnly
* compute.instanceGroups.create
* compute.instanceGroups.delete
* compute.instanceGroups.update
* compute.instanceGroups.use
* calcola.istanze.uso
* compute.regionBackendServices.delete
* compute.regionBackendServices.update
* compute.regionBackendServices.use
* calcola.risorsePolitiche.crea
* compute.resourcePolicies.delete
* compute.resourcePolicies.get
* registrazione.logEntries.route
* config.deployments.create
* config.deployments.delete
* config.deployments.get
* config.deployments.update
* config.revisions.get
* configurazione.distribuzioni.blocco
* config.operations.get




=== 26 novembre 2025

Le autorizzazioni sono state aggiornate per chiarire il loro utilizzo, ma non sono state aggiunte o rimosse autorizzazioni. Sono state aggiunte tre colonne per indicare se ogni autorizzazione viene utilizzata per la distribuzione, le operazioni quotidiane o l'eliminazione. Oltre a ciò, alcune autorizzazioni sono separate in base al loro utilizzo per NetApp Data Classification e NetApp Backup and Recovery.



=== 06 febbraio 2023

A questa policy è stata aggiunta la seguente autorizzazione:

* calcola.istanze.aggiornaInterfaccia di rete


Questa autorizzazione è richiesta per Cloud Volumes ONTAP.



=== 2023-01-27

A questa policy sono state aggiunte le seguenti autorizzazioni:

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.setIamPolicy


Queste autorizzazioni sono necessarie per NetApp Backup and Recovery.
