---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'A seconda delle azioni eseguite nella Console, potresti aver associato le credenziali ONTAP e le credenziali del sito di supporto NetApp (NSS) al tuo accesso utente.  Dopo averle associate, potrai visualizzare e gestire tali credenziali.  Ad esempio, se modifichi la password per queste credenziali, dovrai aggiornare la password nella Console.' 
---
= Gestisci le credenziali associate al tuo accesso NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A seconda delle azioni eseguite nella Console, potresti aver associato le credenziali ONTAP e le credenziali del sito di supporto NetApp (NSS) al tuo accesso utente.  Dopo averle associate, potrai visualizzare e gestire tali credenziali.  Ad esempio, se modifichi la password per queste credenziali, dovrai aggiornare la password nella Console.



== Credenziali ONTAP

Gli utenti necessitano delle credenziali di amministratore ONTAP per individuare i cluster ONTAP nella Console.  Tuttavia, l'accesso a ONTAP System Manager dipende dall'utilizzo o meno di un agente Console.

.Senza un agente Console
Agli utenti viene richiesto di immettere le proprie credenziali ONTAP per accedere a ONTAP System Manager per il cluster.  Gli utenti possono scegliere di salvare queste credenziali nella Console, il che significa che non verrà loro richiesto di immetterle ogni volta.  Le credenziali utente sono visibili solo all'utente interessato e possono essere gestite dalla pagina Credenziali utente.

.Con un agente Console
Per impostazione predefinita, agli utenti non viene richiesto di immettere le proprie credenziali ONTAP per accedere a ONTAP System Manager.  Tuttavia, un amministratore della Console (con il ruolo di amministratore dell'organizzazione) può configurare la Console in modo che richieda agli utenti di immettere le proprie credenziali ONTAP .  Quando questa impostazione è abilitata, gli utenti devono immettere ogni volta le proprie credenziali ONTAP .

link:task-ontap-access-agent.html["Saperne di più."^]



== Credenziali NSS

Le credenziali NSS associate all'accesso alla NetApp Console consentono la registrazione del supporto, la gestione dei casi e l'accesso a Digital Advisor.

* Quando accedi a *Supporto > Risorse* e ti registri per ricevere supporto, ti verrà chiesto di associare le credenziali NSS al tuo login.
+
In questo modo la tua organizzazione o il tuo account vengono registrati per il supporto e viene attivato il diritto al supporto.  Solo un utente nella tua organizzazione deve associare un account NetApp Support Site al proprio login per registrarsi al supporto e attivare il diritto al supporto.  Una volta completata questa operazione, la pagina *Risorse* mostrerà che il tuo account è registrato per l'assistenza.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Scopri come registrarti per ricevere supporto"^]

* Quando accedi a *Amministrazione > Supporto > Gestione casi*, ti verrà chiesto di immettere le tue credenziali NSS, se non l'hai già fatto.  Questa pagina ti consente di creare e gestire i casi di supporto associati al tuo account NSS e alla tua azienda.
* Quando accedi a Digital Advisor nella Console, ti verrà chiesto di effettuare l'accesso a Digital Advisor inserendo le tue credenziali NSS.


Tieni presente quanto segue in merito all'account NSS associato al tuo accesso:

* L'account è gestito a livello utente, il che significa che non è visibile agli altri utenti che effettuano l'accesso.
* Per ogni utente può essere associato un solo account NSS al Digital Advisor e alla gestione dei casi di supporto.
* Se stai provando ad associare un account NetApp Support Site a un sistema Cloud Volumes ONTAP , puoi scegliere solo tra gli account NSS aggiunti all'organizzazione di cui sei membro.
+
Le credenziali a livello di account NSS sono diverse dall'account NSS associato al tuo accesso.  Le credenziali a livello di account NSS consentono di distribuire Cloud Volumes ONTAP con BYOL, registrare sistemi PAYGO e aggiornare il relativo software.

+
link:task-adding-nss-accounts.html["Scopri di più sull'utilizzo delle credenziali NSS con la tua organizzazione o account NetApp Console"] .





== Gestisci le tue credenziali utente

Gestisci le tue credenziali utente aggiornando il nome utente e la password oppure eliminando le credenziali.

.Passi
. Selezionare *Amministrazione > Credenziali*.
. Selezionare *Credenziali utente*.
. Se non disponi ancora di credenziali utente, puoi selezionare *Aggiungi credenziali NSS* per aggiungere il tuo account NetApp Support Site.
. Gestisci le credenziali esistenti scegliendo le seguenti opzioni dal menu Azioni:
+
** *Aggiorna credenziali*: aggiorna il nome utente e la password dell'account.
** *Elimina credenziali*: rimuovi l'account NSS associato al tuo accesso alla Console.



