---
sidebar: sidebar 
permalink: task-maintain-agents.html 
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, connector, connector health 
summary: 'La manutenzione del sistema operativo sull"host dell"agente è responsabilità dell"utente.  Ad esempio, dovresti applicare gli aggiornamenti di sicurezza al sistema operativo sull"host dell"agente Console seguendo le procedure standard della tua azienda per la distribuzione del sistema operativo.' 
---
= Gestire la VM per un agente Console installato manualmente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si installa manualmente un agente Console, la manutenzione del sistema operativo sull'host dell'agente è responsabilità del cliente. Ad esempio, il cliente deve applicare gli aggiornamenti di sicurezza al sistema operativo sull'host dell'agente seguendo le procedure standard aziendali per la distribuzione del sistema operativo.



== Applicare gli aggiornamenti del sistema operativo all'host dell'agente

Applica le patch di sicurezza del sistema operativo senza interrompere i servizi host dell'agente.

Per mantenere la compatibilità con le configurazioni supportate, è consigliabile impedire l'aggiornamento di Docker o Podman durante le normali procedure di applicazione delle patch del sistema operativo. È possibile farlo escludendo temporaneamente Docker o Podman dagli aggiornamenti oppure configurando in modo permanente il gestore di pacchetti in modo che ignori gli aggiornamenti di Docker o Podman.

Di seguito sono riportati alcuni esempi su come escludere gli aggiornamenti di Docker o Podman per diverse distribuzioni Linux. Consulta la documentazione della tua distribuzione Linux per le istruzioni più aggiornate su come escludere i pacchetti dagli aggiornamenti.

.Esempio di Podman
[source, bash]
----
sudo yum update --exclude=podman
sudo yum upgrade
----
.Esempio Docker
[source, bash]
----
sudo apt-mark hold docker-ce docker-ce-cli containerd.io
sudo apt update
sudo apt upgrade
----


== Tipo di VM o istanza

Se si crea un agente Console dalla Console, questo distribuisce un'istanza VM nel provider cloud con una configurazione predefinita.  Dopo aver creato l'agente, non passare a un'istanza VM più piccola con meno CPU o RAM.

Nella tabella seguente sono elencati i requisiti di CPU e RAM:

processore:: 8 core o 8 vCPU
Memoria RAM:: 32 GB


link:reference-agent-default-config.html["Scopri la configurazione predefinita per l'agente"] .



== Monitorare l'agente

La console ti avvisa quando la macchina virtuale dell'agente non è integro, compresi problemi di spazio su disco, RAM e CPU.  Monitora queste notifiche nel Centro notifiche all'interno della Console oppure configura le notifiche e-mail.  È normale che si verifichino occasionalmente aumenti dello spazio su disco, della memoria o dell'utilizzo della CPU, ma se ciò accade frequentemente, è opportuno adottare misure per risolverlo.

Ad esempio, la Console ti avvisa quando una risorsa agente (CPU, RAM o spazio su disco) supera il 90% della sua capacità totale per 30 minuti consecutivi.  Successivamente, se l'utilizzo delle risorse scende al di sotto di tale soglia, la notifica viene visualizzata come risolta (verde) nel Centro notifiche.


NOTE: Collabora con il supporto NetApp se hai domande sulla modifica della tua VM agente.

link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#notification-center["Saperne di più."^]

[cols="47,47"]
|===
| Notifica | Azione necessaria 


| Lo spazio su disco è troppo alto | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["Rivedi l'articolo della Knowledge Base NetApp"^] . 


| L'utilizzo della CPU è troppo elevato | Aumenta le dimensioni della CPU della VM dell'agente nel tuo provider cloud o in locale, a seconda di dove l'hai installata.  In alternativa, è possibile creare agenti aggiuntivi e distribuire il carico di lavoro tra più agenti.  L'utilizzo della RAM può variare in base all'ambiente, ai carichi di lavoro ONTAP , al numero di sistemi Cloud Volumes ONTAP e ai servizi dati utilizzati. 


| L'utilizzo della RAM è troppo elevato | Aumenta la RAM della VM dell'agente nel tuo provider cloud o in locale, a seconda di dove l'hai installata.  In alternativa, è possibile creare agenti aggiuntivi e distribuire il carico di lavoro tra più agenti.  L'utilizzo della RAM può variare in base all'ambiente, ai carichi di lavoro ONTAP , al numero di sistemi Cloud Volumes ONTAP e ai servizi dati utilizzati. 
|===


== Arresto e avvio della VM dell'agente

Se necessario, arrestare e avviare la VM dell'agente tramite la console del provider cloud o le procedure standard in sede.

link:concept-agents.html#agents-must-be-operational-at-all-times["Tieni presente che l'agente della console deve essere sempre operativo"] .



== Connettiti alla VM Linux

Se devi connetterti alla VM Linux su cui è in esecuzione l'agente, utilizza le opzioni di connettività del tuo provider cloud.

AWS:: Quando si crea l'istanza dell'agente in AWS, fornire una chiave di accesso AWS e una chiave segreta.  È possibile utilizzare questa coppia di chiavi per connettersi tramite SSH all'istanza.  Utilizzare il nome utente 'ubuntu' per l'istanza EC2 Linux.  Per gli agenti creati prima di maggio 2023, utilizzare il nome utente 'ec2-user'.
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["Documentazione AWS: connettiti alla tua istanza Linux"^]

--
Azzurro:: Quando si crea la macchina virtuale dell'agente in Azure, si specifica un nome utente e si sceglie di autenticarsi con una password o una chiave pubblica SSH.  Utilizza il metodo di autenticazione scelto per connetterti alla VM.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Documentazione di Azure: accesso SSH alla macchina virtuale"^]

--
Google Cloud:: Non è possibile specificare un metodo di autenticazione quando si crea un agente in Google Cloud.  Tuttavia, puoi connetterti all'istanza della VM Linux tramite Google Cloud Console o Google Cloud CLI (gcloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: connessione alle VM Linux"^]

--

