---
sidebar: sidebar 
permalink: task-upgrade-agent.html 
keywords: upgrade, manual upgrade, agent upgrade, manual agent upgrade, upgrade agent manually, private mode upgrade, offline upgrade, upgrade private mode, connector upgrade, agent upgrade 
summary: 'L"agente della Console viene aggiornato automaticamente quando dispone di connettività outbound. Se l"agente della Console non dispone di connettività outbound, è possibile aggiornarlo manualmente (ad esempio, in modalità privata).' 
---
= Gestisci gli aggiornamenti degli agenti della console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'agente della Console viene aggiornato automaticamente quando dispone di connettività outbound. Se l'agente della Console non dispone di connettività outbound, è possibile aggiornarlo manualmente (ad esempio, in modalità privata).



== Aggiorna l'agente della console

Durante il processo di aggiornamento, l'agente della console deve essere riavviato, pertanto la NetApp Console non sarà disponibile durante l'aggiornamento.

.Passi
. Scarica il software dell'agente Console da https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sito di supporto NetApp"^] .
. Copiare il programma di installazione sull'host Linux.
. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x /path/NetApp-Console-Agent-Offline-<version>
----
+
Dove <versione> è la versione dell'agente Console scaricato.

. Eseguire lo script di installazione:
+
[source, cli]
----
sudo /path/NetApp-Console-Agent-Offline-<version>
----
+
Dove <versione> è la versione dell'agente scaricato.

. Una volta completato l'aggiornamento, puoi verificare la versione dell'agente andando su *Amministrazione > Supporto > Agenti*.

