---
sidebar: sidebar 
permalink: task-install-agent-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: 'Per installare manualmente l"agente Console sul tuo host Linux, devi esaminare i requisiti dell"host, configurare la rete, preparare le autorizzazioni di Google Cloud, abilitare le API di Google Cloud, installare la Console e quindi fornire le autorizzazioni preparate.' 
---
= Distribuisci manualmente l'agente Console in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per distribuire manualmente l'agente Console sul proprio host Linux, è necessario verificare i requisiti dell'host, configurare la rete, preparare le autorizzazioni di Google Cloud, abilitare le API di Google Cloud, installare la Console e infine fornire le autorizzazioni precedentemente predisposte.

L'installazione di un agente in Google Cloud avvia un'istanza di macchina virtuale con Linux e il software dell'agente Console in una VPC a tua scelta.

.Prima di iniziare
* link:concept-agent-install-options.html#agent-cloud-manual-deploy["Scopri quando effettuare il deployment manuale in Google Cloud"].
* Dovresti rivederelink:reference-limitations.html["Limitazioni dell'agente della console"] .




== Passaggio 1: rivedere i requisiti dell'host

Il software dell'agente Console deve essere eseguito su un host che soddisfi specifici requisiti del sistema operativo, requisiti di RAM, requisiti di porta e così via.


NOTE: L'agente della console riserva l'intervallo UID e GID da 19000 a 19200.  Questo intervallo è fisso e non può essere modificato.  Se un software di terze parti sul tuo host utilizza UID o GID compresi in questo intervallo, l'installazione dell'agente non andrà a buon fine.  NetApp consiglia di utilizzare un host privo di software di terze parti per evitare conflitti.

Host dedicato:: L'agente Console richiede un host dedicato.  È supportata qualsiasi architettura che soddisfi i seguenti requisiti dimensionali:
+
--
* CPU: 8 core o 8 vCPU
* RAM: 32 GB
* Spazio su disco: si consigliano 165 GB per l'host, con i seguenti requisiti di partizione:
+
** `/opt`: Devono essere disponibili 120 GiB di spazio
+
L'agente utilizza `/opt` per installare il `/opt/application/netapp` directory e il suo contenuto.

** `/var`: Devono essere disponibili 40 GiB di spazio
+
L'agente della Console richiede questo spazio in `/var` perché Podman o Docker sono progettati per creare i container all'interno di questa directory. Nello specifico, creeranno i container nella `/var/lib/containers/storage` directory e `/var/lib/docker` per Docker. I mount esterni o i collegamenti simbolici non funzionano per questo spazio.





--
Tipo di macchina Google Cloud:: Un tipo di istanza che soddisfa i requisiti di CPU e RAM. NetApp consiglia n2-standard-8.
+
--
L'agente Console è supportato in Google Cloud su un'istanza VM con un sistema operativo che supporta https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Funzionalità della VM schermata"^]

--
Ipervisore:: È richiesto un hypervisor bare metal o hosted certificato per eseguire un sistema operativo supportato.
[[podman-versions]]Requisiti del sistema operativo e del contenitore:: L'agente Console è supportato con i seguenti sistemi operativi quando si utilizza la Console in modalità standard o in modalità limitata.  Prima di installare l'agente è necessario uno strumento di orchestrazione dei container.


[cols="2a,2a,2a,2a,2a"]
|===
| Sistema operativo | Versioni del sistema operativo supportate | Versioni dell'agente supportate | Strumento contenitore richiesto | SELinux 


 a| 
Red Hat Enterprise Linux



 a| 
 a| 
9,6

* Solo versioni in lingua inglese.
* L'host deve essere registrato presso Red Hat Subscription Management.  Se non è registrato, l'host non può accedere ai repository per aggiornare il software di terze parti richiesto durante l'installazione dell'agente.

 a| 
4.0.0 o versione successiva con la console in modalità standard o modalità limitata
 a| 
Podman versione 5.4.0 con podman-compose 1.5.0.

<<podman-configuration,Visualizza i requisiti di configurazione di Podman>> .
 a| 
Supportato in modalità di applicazione o modalità permissiva



 a| 
 a| 
da 9,1 a 9,4

* Solo versioni in lingua inglese.
* L'host deve essere registrato presso Red Hat Subscription Management.  Se non è registrato, l'host non può accedere ai repository per aggiornare il software di terze parti richiesto durante l'installazione dell'agente.

 a| 
3.9.50 o versione successiva con la Console in modalità standard o modalità limitata
 a| 
Podman versione 4.9.4 con podman-compose 1.5.0.

<<podman-configuration,Visualizza i requisiti di configurazione di Podman>> .
 a| 
Supportato in modalità di applicazione o modalità permissiva



 a| 
 a| 
da 8,6 a 8,10

* Solo versioni in lingua inglese.
* L'host deve essere registrato presso Red Hat Subscription Management.  Se non è registrato, l'host non può accedere ai repository per aggiornare il software di terze parti richiesto durante l'installazione dell'agente.

 a| 
3.9.50 o versione successiva con la Console in modalità standard o modalità limitata
 a| 
Podman versione 4.6.1 o 4.9.4 con podman-compose 1.0.6.

<<podman-configuration,Visualizza i requisiti di configurazione di Podman>> .
 a| 
Supportato in modalità di applicazione o modalità permissiva



 a| 
Ubuntu



 a| 
 a| 
24,04 LTS
 a| 
3.9.45 o versione successiva con la NetApp Console in modalità standard o in modalità limitata
 a| 
Docker Engine dalla versione 23.0.6 alla 28.0.0.
 a| 
Non supportato



 a| 
 a| 
22,04 LTS
 a| 
3.9.50 o successivo
 a| 
Docker Engine dalla versione 23.0.6 alla 28.0.0.
 a| 
Non supportato

|===


== Passaggio 2: installare Podman o Docker Engine

A seconda del sistema operativo in uso, prima di installare l'agente è necessario utilizzare Podman o Docker Engine.

* Podman è richiesto per Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Visualizza le versioni di Podman supportate>> .

* Docker Engine è richiesto per Ubuntu.
+
<<podman-versions,Visualizza le versioni supportate di Docker Engine>> .



.Passi
[role="tabbed-block"]
====
.Podman
--
Per installare e configurare Podman, segui questi passaggi:

* Abilita e avvia il servizio podman.socket
* Installa python3
* Installa il pacchetto podman-compose (la procedura varia a seconda della versione di Red Hat)
* Aggiungere podman-compose alla variabile d'ambiente PATH
* Se si utilizza Red Hat Enterprise Linux, verificare che la versione di Podman utilizzi Netavark Aardvark DNS anziché CNI



NOTE: Dopo aver installato l'agente, regolare la porta aardvark-dns (predefinita: 53) per evitare conflitti di porta DNS.  Seguire le istruzioni per configurare la porta.

.Passi
. Rimuovere il pacchetto podman-docker se è installato sull'host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Installa Podman.
+
È possibile ottenere Podman dai repository ufficiali di Red Hat Enterprise Linux.

+
.. Per Red Hat Enterprise Linux 9,6:
+
[source, cli]
----
sudo dnf install podman-5:<version>
----
+
Dove <versione> è la versione supportata di Podman che stai installando. <<podman-versions,Visualizza le versioni di Podman supportate>> .

.. Per Red Hat Enterprise Linux dalla versione 9.1 alla 9.4:
+
[source, cli]
----
sudo dnf install podman-4:<version>
----
+
Dove <versione> è la versione supportata di Podman che stai installando. <<podman-versions,Visualizza le versioni di Podman supportate>> .

.. Per Red Hat Enterprise Linux 8:
+
[source, cli]
----
sudo dnf install podman-4:<version>
----
+
Dove <versione> è la versione supportata di Podman che stai installando. <<podman-versions,Visualizza le versioni di Podman supportate>> .



. Abilitare e avviare il servizio podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Installa python3.
+
[source, cli]
----
sudo dnf install python3
----
. Installa il pacchetto repository EPEL se non è già disponibile sul tuo sistema.
+
Questo passaggio è necessario perché podman-compose è disponibile nel repository Extra Packages for Enterprise Linux (EPEL).

. Se si utilizza Red Hat Enterprise 9:
+
.. Installare il pacchetto del repository EPEL.


+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
.. Installa il pacchetto podman-compose 1.5.0.
+
[source, cli]
----
sudo dnf install podman-compose-1.5.0
----


. Se si utilizza Red Hat Enterprise Linux 8:
+
.. Installare il pacchetto del repository EPEL.
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
.. Installa il pacchetto podman-compose 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Utilizzando il `dnf install` il comando soddisfa il requisito per aggiungere podman-compose alla variabile d'ambiente PATH.  Il comando di installazione aggiunge podman-compose a /usr/bin, che è già incluso nel `secure_path` opzione sull'host.

.. Se si utilizza Red Hat Enterprise Linux 8, verificare che la versione di Podman utilizzi NetAvark con Aardvark DNS anziché CNI.
+
... Controlla se il tuo networkBackend è impostato su CNI eseguendo il seguente comando:
+
[source, cli]
----
podman info | grep networkBackend
----
... Se networkBackend è impostato su `CNI` , dovrai cambiarlo in `netavark` .
... Installare `netavark` E `aardvark-dns` utilizzando il seguente comando:
+
[source, cli]
----
dnf install aardvark-dns netavark
----
... Apri il `/etc/containers/containers.conf` file e modificare l'opzione network_backend per utilizzare "netavark" invece di "cni".
+
Se `/etc/containers/containers.conf` non esiste, apportare le modifiche alla configurazione `/usr/share/containers/containers.conf` .

... Riavvia Podman.
+
[source, cli]
----
systemctl restart podman
----
... Verificare che networkBackend sia ora modificato in "netavark" utilizzando il seguente comando:
+
[source, cli]
----
podman info | grep networkBackend
----






--
.Motore Docker
--
Per installare Docker Engine, seguire la documentazione di Docker.

.Passi
. https://docs.docker.com/engine/install/["Visualizza le istruzioni di installazione da Docker"^]
+
Segui i passaggi per installare una versione supportata di Docker Engine. Non installare la versione più recente, poiché non è supportata dalla Console.

. Verificare che Docker sia abilitato e in esecuzione.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Passaggio 3: configurazione della rete

Configura la tua rete in modo che l'agente della console possa gestire risorse e processi all'interno del tuo ambiente cloud ibrido.  Ad esempio, è necessario assicurarsi che le connessioni siano disponibili per le reti di destinazione e che sia disponibile l'accesso a Internet in uscita.

Connessioni alle reti di destinazione:: L'agente Console richiede una connessione di rete alla posizione in cui si prevede di creare e gestire i sistemi.  Ad esempio, la rete in cui intendi creare sistemi Cloud Volumes ONTAP o un sistema di archiviazione nel tuo ambiente locale.


Accesso a Internet in uscita:: La posizione di rete in cui si distribuisce l'agente Console deve disporre di una connessione Internet in uscita per contattare endpoint specifici.


Endpoint contattati dai computer quando si utilizza la NetApp Console basata sul Web::
+
--
I computer che accedono alla Console tramite un browser web devono essere in grado di contattare diversi endpoint.

link:reference-networking-saas-console.html["Preparare la rete per la NetApp Console"].

--


Endpoint contattati dall'agente della console:: L'agente della console necessita di accesso a Internet in uscita per contattare i seguenti endpoint per gestire risorse e processi all'interno dell'ambiente cloud pubblico per le operazioni quotidiane.
+
--
Gli endpoint elencati di seguito sono tutti voci CNAME.

[cols="2a,1a"]
|===
| Punti finali | Scopo 


 a| 
\ https://www.googleapis.com/compute/v1/ \ https://compute.googleapis.com/compute/v1 \ https://cloudresourcemanager.googleapis.com/v1/projects \ https://www.googleapis.com/compute/beta \ https://storage.googleapis.com/storage/v1 \ https://www.googleapis.com/storage/v1 \ https://iam.googleapis.com/v1 \ https://cloudkms.googleapis.com/v1 \ https://config.googleapis.com/v1/projects
 a| 
Per gestire le risorse in Google Cloud.



 a| 
\ https://mysupport.netapp.com
 a| 
Per ottenere informazioni sulle licenze e per inviare messaggi AutoSupport a NetApp Support.



 a| 
\ https://signin.b2c.netapp.com
 a| 
Per aggiornare le credenziali del sito di supporto NetApp (NSS) o per aggiungere nuove credenziali NSS alla NetApp Console.



 a| 
\ https://support.netapp.com
 a| 
Per ottenere informazioni sulle licenze e per inviare messaggi AutoSupport a NetApp Support, nonché per ricevere aggiornamenti software per Cloud Volumes ONTAP.



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com
 a| 
Per fornire funzionalità e servizi all'interno della NetApp Console.



 a| 
https://bluexpinfraprod.eastus2.data.azurecr.io https://bluexpinfraprod.azurecr.io https://occmclientinfragov.azurecr.us (necessario per le implementazioni in modalità limitata)
 a| 
Per ottenere immagini per gli aggiornamenti dell'agente della console.

|===
--


Server proxy:: NetApp supporta sia configurazioni proxy esplicite che trasparenti.  Se si utilizza un proxy trasparente, è necessario fornire solo il certificato per il server proxy.  Se si utilizza un proxy esplicito, saranno necessari anche l'indirizzo IP e le credenziali.
+
--
* indirizzo IP
* Credenziali
* Certificato HTTPS


--


porti:: Non c'è traffico in entrata verso l'agente della Console, a meno che non venga avviato dall'utente o utilizzato come proxy per inviare AutoSupport messaggi da Cloud Volumes ONTAP al supporto NetApp.
+
--
* HTTP (80) e HTTPS (443) forniscono l'accesso all'interfaccia utente locale, che utilizzerai in rare circostanze.
* SSH (22) è necessario solo se è necessario connettersi all'host per la risoluzione dei problemi.
* Le connessioni in ingresso sulla porta 3128 sono necessarie se si distribuiscono sistemi Cloud Volumes ONTAP in una subnet in cui non è disponibile una connessione Internet in uscita.
+
Se i sistemi Cloud Volumes ONTAP non dispongono di una connessione Internet in uscita per inviare messaggi AutoSupport , la Console configura automaticamente tali sistemi per utilizzare un server proxy incluso nell'agente della Console.  L'unico requisito è assicurarsi che il gruppo di sicurezza dell'agente Console consenta connessioni in entrata sulla porta 3128.  Sarà necessario aprire questa porta dopo aver distribuito l'agente Console.



--


Abilita NTP:: Se si intende utilizzare NetApp Data Classification per analizzare le fonti di dati aziendali, è necessario abilitare un servizio Network Time Protocol (NTP) sia sull'agente della Console che sul sistema NetApp Data Classification, in modo che l'ora sia sincronizzata tra i sistemi. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Scopri di più su NetApp Data Classification"^]




== Passaggio 4: impostare le autorizzazioni per l'agente della console

È necessario un account di servizio Google Cloud per fornire all'agente della Console le autorizzazioni di cui la Console ha bisogno per gestire le risorse in Google Cloud.  Quando si crea l'agente Console, è necessario associare questo account di servizio alla VM dell'agente Console.

È tua responsabilità aggiornare il ruolo personalizzato man mano che vengono aggiunte nuove autorizzazioni nelle versioni successive.  Se saranno necessarie nuove autorizzazioni, queste saranno elencate nelle note di rilascio.

.Passi
. Crea un ruolo personalizzato in Google Cloud:
+
.. Crea un file YAML che includa il contenuto dellink:reference-permissions-gcp.html["autorizzazioni dell'account di servizio per l'agente della console"] .
.. Da Google Cloud, attiva Cloud Shell.
.. Carica il file YAML che include le autorizzazioni richieste.
.. Crea un ruolo personalizzato utilizzando `gcloud iam roles create` comando.
+
L'esempio seguente crea un ruolo denominato "agente" a livello di progetto:

+
[source, shell]
----
gcloud iam roles create agent --project=myproject --file=agent.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentazione di Google Cloud: creazione e gestione di ruoli personalizzati"^]



. Crea un account di servizio in Google Cloud e assegna il ruolo all'account di servizio:
+
.. Dal servizio IAM e amministrazione, seleziona *Account di servizio > Crea account di servizio*.
.. Inserisci i dettagli dell'account di servizio e seleziona *Crea e continua*.
.. Seleziona il ruolo che hai appena creato.
.. Completa i passaggi rimanenti per creare l'account di servizio.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentazione di Google Cloud: creazione di un account di servizio"^]



. Se si prevede di distribuire sistemi Cloud Volumes ONTAP in progetti diversi da quello in cui risiede l'agente della Console, sarà necessario concedere all'account di servizio dell'agente della Console l'accesso a tali progetti.
+
Ad esempio, supponiamo che l'agente Console si trovi nel progetto 1 e che si desideri creare sistemi Cloud Volumes ONTAP nel progetto 2.  Sarà necessario concedere l'accesso all'account di servizio nel progetto 2.

+
.. Dal servizio IAM e amministrazione, seleziona il progetto Google Cloud in cui desideri creare i sistemi Cloud Volumes ONTAP .
.. Nella pagina *IAM*, seleziona *Concedi accesso* e fornisci i dettagli richiesti.
+
*** Inserisci l'email dell'account di servizio dell'agente della console.
*** Selezionare il ruolo personalizzato dell'agente della console.
*** Seleziona *Salva*.




+
Per maggiori dettagli, fare riferimento a https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentazione di Google Cloud"^]





== Passaggio 5: impostare le autorizzazioni VPC condivise

Se si utilizza una VPC condivisa per distribuire risorse in un progetto di servizio, sarà necessario preparare le autorizzazioni.

Questa tabella è di riferimento e il tuo ambiente dovrebbe riflettere la tabella delle autorizzazioni una volta completata la configurazione IAM.

.Visualizza le autorizzazioni VPC condivise
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identità | Creatore | Ospitato in | Autorizzazioni del progetto di servizio | Autorizzazioni del progetto host | Scopo 


| Account Google per distribuire l'agente | Costume | Progetto di servizio  a| 
link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Politica di distribuzione degli agenti"]
 a| 
compute.networkUser
| Distribuzione dell'agente nel progetto di servizio 


| account di servizio agente | Costume | Progetto di servizio  a| 
link:reference-permissions-gcp.html["Politica dell'account del servizio agente"]
| compute.networkUser deploymentmanager.editor | Distribuzione e manutenzione di Cloud Volumes ONTAP e dei servizi nel progetto di servizio 


| Account di servizio Cloud Volumes ONTAP | Costume | Progetto di servizio | membro storage.admin: account di servizio NetApp Console come serviceAccount.user | N / A | (Facoltativo) Per NetApp Cloud Tiering e NetApp Backup and Recovery 


| Agente di servizio delle API di Google | Google Cloud | Progetto di servizio  a| 
(Predefinito) Editor
 a| 
compute.networkUser
| Interagisce con le API di Google Cloud per conto della distribuzione.  Consente alla Console di utilizzare la rete condivisa. 


| Account di servizio predefinito di Google Compute Engine | Google Cloud | Progetto di servizio  a| 
(Predefinito) Editor
 a| 
compute.networkUser
| Distribuisce istanze di Google Cloud e infrastrutture di elaborazione per conto della distribuzione.  Consente alla Console di utilizzare la rete condivisa. 
|===
Note:

. `deploymentmanager.editor`È richiesto solo nel progetto host se non si passano regole firewall alla distribuzione e si sceglie di lasciare che la Console le crei per te. La NetApp Console crea una distribuzione nel progetto host che contiene la regola firewall VPC0 se non viene specificata alcuna regola.
. `firewall.create` e  `firewall.delete` sono necessarie solo se non si passano regole firewall alla distribuzione e si sceglie di lasciare che sia la Console a crearle per te. Queste autorizzazioni risiedono nel file .yaml dell'account della Console. Se si distribuisce una coppia HA utilizzando una VPC condivisa, queste autorizzazioni verranno utilizzate per creare le regole firewall per VPC1, 2 e 3. Per tutte le altre distribuzioni, queste autorizzazioni verranno utilizzate anche per creare le regole per VPC0.
. Per Cloud Tiering, l'account di servizio di tiering deve avere il  `serviceAccount.user` ruolo sull'account di servizio, non solo a livello di progetto. Se lo assegni  `serviceAccount.user` a livello di progetto, le autorizzazioni non vengono visualizzate quando interroghi l'account di servizio con  `getIAMPolicy`.


====


== Passaggio 6: abilita le API di Google Cloud

Prima di poter distribuire un agente Console in Google Cloud, è necessario abilitare diverse API di Google Cloud.

.Fare un passo
. Abilita le seguenti API di Google Cloud nel tuo progetto:
+
** API Cloud Build (necessaria per le distribuzioni Cloud Volumes ONTAP in modalità privata tramite Infrastructure Manager)
** API di Cloud Deployment Manager V2
** API di Cloud Infrastructure Manager
** API di registrazione cloud
** API di Cloud Resource Manager
** API di Compute Engine
** API di gestione dell'identità e dell'accesso (IAM)
** Cloud Key Management Service (KMS) API (necessaria solo se si prevede di utilizzare NetApp Backup and Recovery con chiavi di crittografia gestite dal cliente (CMEK))
** Cloud Quotas API (necessaria per le distribuzioni Cloud Volumes ONTAP tramite Infrastructure Manager)




https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentazione di Google Cloud: abilitazione delle API"^]



== Passaggio 7: installare l'agente della console

Una volta completati i prerequisiti, puoi installare manualmente il software sul tuo host Linux.

Quando si distribuisce un agente, il sistema crea anche un bucket Google Cloud per archiviare i file di distribuzione.

.Prima di iniziare
Dovresti avere quanto segue:

* Privilegi di root per installare l'agente Console.
* Dettagli su un server proxy, se è necessario un proxy per l'accesso a Internet dall'agente della console.
+
È possibile configurare un proxy server dopo l'installazione, ma ciò richiede il riavvio dell'agente della Console.

* Un certificato firmato da una CA, se il server proxy utilizza HTTPS o se il proxy è un proxy di intercettazione.



NOTE: Non è possibile impostare un certificato per un server proxy trasparente durante l'installazione manuale dell'agente Console. Se è necessario impostare un certificato per un server proxy trasparente, è necessario utilizzare la Console di manutenzione dopo l'installazione. Scopri di più sulink:reference-agent-maint-console-proxy.html["Console di manutenzione dell'agente"] .

.Informazioni su questo compito
Dopo l'installazione, l'agente Console si aggiorna automaticamente se è disponibile una nuova versione.

.Passi
. Se le variabili di sistema _http_proxy_ o _https_proxy_ sono impostate sull'host, rimuoverle:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se non si rimuovono queste variabili di sistema, l'installazione fallirà.

. Scaricare il software dell'agente Console e copiarlo sull'host Linux.  È possibile scaricarlo dalla NetApp Console o dal sito di supporto NetApp .
+
** NetApp Console: Vai a *Agenti > Gestione > Distribuisci agente > Locale > Installazione manuale*.
+
Scegli se scaricare i file di installazione dell'agente o un URL per i file.

** https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["Sito di supporto NetApp"^] (necessario se non si ha già accesso alla Console).
+

NOTE: Scarica il programma di installazione dell'agente "online" pensato per l'utilizzo nella tua rete o nel cloud. È disponibile un programma di installazione "offline" separato per l'agente Console, ma è supportato solo con distribuzioni in modalità privata.

** NetApp Support Site (necessario se non si ha già accesso alla Console) https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["Sito di supporto NetApp"^].


. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Dove <versione> è la versione dell'agente Console scaricato.

. Se si esegue l'installazione in un ambiente Government Cloud, disattivare i controlli di configurazione.link:task-troubleshoot-agent.html#disable-config-check["Scopri come disattivare i controlli di configurazione per le installazioni manuali."]
. Eseguire lo script di installazione.
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Sarà necessario aggiungere le informazioni sul proxy se la rete richiede un proxy per l'accesso a Internet. È possibile aggiungere un proxy esplicito durante l'installazione. I parametri  `--proxy` e  `--cacert` sono facoltativi e non verrà richiesto di aggiungerli. Se si dispone di un proxy server esplicito, sarà necessario immettere i parametri come mostrato.

+

NOTE: Se desideri configurare un proxy trasparente, puoi farlo dopo l'installazione. link:reference-agent-maint-console-proxy.html["Scopri di più sulla console di manutenzione dell'agente"].

+
Ecco un esempio di configurazione di un proxy server esplicito con un certificato firmato da una CA:

+
[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`Configura l'agente della Console per utilizzare un proxy server utilizzando uno dei seguenti formati:

+
** \http://indirizzo:porta
** \http://nome-utente:password@indirizzo:porta
** \http://nome-dominio%92nome-utente:password@indirizzo:porta
** \https://indirizzo:porta
** \https://nome-utente:password@indirizzo:porta
** \https://nome-dominio%92nome-utente:password@indirizzo:porta
+
Notare quanto segue:

+
*** L'utente può essere un utente locale o un utente di dominio.
*** Per un utente di dominio, è necessario utilizzare il codice ASCII per \ come mostrato sopra.
*** L'agente Console non supporta nomi utente o password che includono il carattere @.
*** Se la password include uno qualsiasi dei seguenti caratteri speciali, è necessario anteporre una barra rovesciata a tale carattere speciale: & o !
+
Per esempio:

+
\http://bxpproxyuser:netapp1\!@indirizzo:3128





. Se hai utilizzato Podman, dovrai modificare la porta aardvark-dns.
+
.. Eseguire l'SSH sulla macchina virtuale dell'agente Console.
.. Aprire il file podman _/usr/share/containers/containers.conf_ e modificare la porta scelta per il servizio DNS Aardvark.  Ad esempio, cambialo in 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
Per esempio:

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. Riavviare la macchina virtuale dell'agente Console.


. Attendi il completamento dell'installazione.
+
Al termine dell'installazione, il servizio agente della console (occm) viene riavviato due volte se è stato specificato un server proxy.

+

NOTE: Se l'installazione non riesce, puoi visualizzare il report e i registri di installazione per aiutarti a risolvere i problemi.link:task-troubleshoot-agent.html#troubleshoot-installation["Scopri come risolvere i problemi di installazione."]

. Aprire un browser Web da un host che dispone di una connessione alla macchina virtuale dell'agente Console e immettere il seguente URL:
+
https://_ipaddress_[]

. Dopo aver effettuato l'accesso, configura l'agente Console:
+
.. Specificare l'organizzazione da associare all'agente Console.
.. Inserisci un nome per il sistema.
.. In *Stai utilizzando un ambiente protetto?* mantieni disattivata la modalità con restrizioni.
+
È consigliabile disattivare la modalità limitata perché questi passaggi descrivono come utilizzare la Console in modalità standard.  Dovresti abilitare la modalità limitata solo se disponi di un ambiente sicuro e desideri disconnettere questo account dai servizi backend.  Se è così,link:task-quick-start-restricted-mode.html["segui i passaggi per iniziare a utilizzare la NetApp Console in modalità limitata"] .

.. Seleziona *Iniziamo*.


+

NOTE: Se l'installazione non riesce, è possibile visualizzare i registri e un report per risolvere il problema.link:task-troubleshoot-agent.html#troubleshoot-installation["Scopri come risolvere i problemi di installazione."]



Se disponi di bucket Google Cloud Storage nello stesso account Google Cloud in cui hai creato l'agente Console, vedrai automaticamente un sistema Google Cloud Storage apparire nella pagina *Sistemi*. https://docs.netapp.com/us-en/storage-management-google-cloud-storage/index.html["Scopri come gestire Google Cloud Storage dalla NetApp Console"^]



== Passaggio 8: fornire le autorizzazioni all'agente della console

È necessario fornire all'agente della console le autorizzazioni Google Cloud configurate in precedenza.  Fornendo le autorizzazioni, l'agente della console può gestire i dati e l'infrastruttura di archiviazione in Google Cloud.

.Passi
. Vai al portale di Google Cloud e assegna l'account di servizio all'istanza VM dell'agente Console.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentazione di Google Cloud: modifica dell'account di servizio e degli ambiti di accesso per un'istanza"^]

. Se desideri gestire le risorse in altri progetti Google Cloud, concedi l'accesso aggiungendo l'account di servizio con il ruolo di agente della console a quel progetto.  Sarà necessario ripetere questo passaggio per ogni progetto.

