---
sidebar: sidebar 
permalink: task-update-agent-addressing.html 
keywords: agent ip address, agent uri, change ip address, edit uri, agent network, agent addressing 
summary: 'Quando la configurazione di rete cambia, potrebbe essere necessario aggiornare l"indirizzo IP dell"agente presso il cloud provider e i relativi URI registrati nella Console.' 
---
= Aggiornare gli indirizzi e gli URI dell'agente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando la configurazione di rete cambia, potrebbe essere necessario aggiornare l'indirizzo IP dell'agente presso il cloud provider e i relativi URI registrati nella Console.



== Cambiare l'indirizzo IP di un agente

Se necessario, puoi modificare gli indirizzi IP interni e pubblici dell'istanza dell'agente assegnata dal tuo provider cloud.

.Passi
. Segui le istruzioni del tuo provider cloud per modificare l'indirizzo IP locale o l'indirizzo IP pubblico (o entrambi) per l'istanza dell'agente.
. Riavviare l'istanza dell'agente per registrare un nuovo indirizzo IP pubblico con la console.
. Se hai modificato l'indirizzo IP privato, aggiorna il percorso di backup per i file di configurazione Cloud Volumes ONTAP in modo che i backup vengano inviati al nuovo indirizzo IP privato sull'agente.
+
Aggiornare la posizione di backup per ciascun sistema Cloud Volumes ONTAP .

+
.. Dalla CLI Cloud Volumes ONTAP , impostare il livello di privilegio su avanzato:




[listing]
----
set -privilege advanced
----
. Eseguire il seguente comando per visualizzare la destinazione di backup corrente:


[listing]
----
system configuration backup settings show
----
. Eseguire il seguente comando per aggiornare l'indirizzo IP della destinazione di backup:


[listing]
----
system configuration backup settings modify -destination <target-location>
----


== Modificare gli URI di un agente

Aggiornare l'URI di un agente della Console qualora cambino i requisiti di rete. Ciò garantisce una gestione ininterrotta, sicura e conforme dell'infrastruttura di storage.

.Passi
. Selezionare *Amministrazione > Agenti*.
. Nella pagina *Panoramica*, seleziona il menu azioni per un agente della console e seleziona *Modifica agente*.
+
Per modificarlo, l'agente della console deve essere attivo.

. Espandi la barra *URI agente* per visualizzare gli URI agente.
. Aggiungi e rimuovi gli URI, quindi seleziona *Applica*.

