---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: Gestisci i membri della tua organizzazione per fornire autorizzazioni ai diversi livelli della gerarchia delle risorse della tua organizzazione. 
---
= Aggiungere utenti a un'organizzazione NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
All'interno della Console, puoi concedere agli utenti l'accesso a progetti o cartelle in base a un ruolo di accesso. Un _ruolo di accesso_ contiene un set di autorizzazioni che consente a un membro (account utente o di servizio) di eseguire azioni specifiche al livello assegnato della gerarchia delle risorse.

.Ruoli di accesso richiesti
Super amministratore, amministratore dell'organizzazione o amministratore di cartelle o progetti (per le cartelle e i progetti che amministrano). link:reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso"].



== Scopri come viene concesso l'accesso nella NetApp Console

NetApp Console utilizza il controllo degli accessi basato sui ruoli (RBAC) per gestire le autorizzazioni. Assegnare ruoli agli utenti individualmente o tramite gruppi federati. Ogni ruolo definisce le azioni consentite per risorse specifiche.

Tenere presente quanto segue in merito alla concessione dell'accesso nella NetApp Console:

* Tutti gli utenti devono prima registrarsi alla NetApp Console prima che possa essere loro concesso l’accesso alle risorse, anche se fanno parte di un gruppo federato.
* È necessario assegnare esplicitamente un ruolo a ciascun utente nella Console prima che possa accedere alle risorse, anche se è membro di un gruppo federato a cui è stato assegnato un ruolo.
* È possibile aggiungere account di servizio direttamente dalla Console e assegnare loro ruoli.




== Aggiungi membri alla tua organizzazione

NetApp Console supporta tre tipi di membri: account utente, account di servizio e gruppi federati.

Gli utenti devono registrarsi a NetApp Console prima di poterli aggiungere e assegnare un ruolo, anche se fanno parte di un gruppo federato. Crea account di servizio direttamente nella Console.

Per poter accedere alle risorse, a tutti i membri deve essere assegnato esplicitamente almeno un ruolo.

Quando aggiungi un membro, scegli il livello della risorsa (organizzazione, cartella o progetto) e assegna un ruolo o più ruoli con le autorizzazioni necessarie.



=== Aggiungi un utente

Gli utenti si iscrivono alla NetApp Console, ma un amministratore dell'organizzazione o un amministratore di cartella o di progetto deve aggiungerli a un'organizzazione, una cartella o un progetto affinché possano accedere alle risorse.

.Prima di iniziare:
L'utente deve essersi già registrato alla NetApp Console. Se non si sono ancora registrati, indirizzali a link:task-sign-up-saas.html["iscriviti alla NetApp Console."]


NOTE: Se si aggiunge un utente che fa parte di un gruppo federato, assicurarsi che l'utente si sia già registrato alla NetApp Console e che gli sia stato assegnato esplicitamente un ruolo nella Console. NetApp consiglia di assegnare un ruolo di accesso minimo, ad esempio Visualizzatore dell'organizzazione.

.Passi
. Selezionare *Amministrazione > Identità e accesso*.
. Seleziona *Membri*.
. Seleziona *Aggiungi un membro*.
. Per *Tipo di membro*, mantenere selezionato *Utente*.
. Per *Email dell'utente*, inserisci l'indirizzo email dell'utente associato all'accesso che ha creato.
. Utilizzare la sezione *Seleziona un'organizzazione, una cartella o un progetto* per scegliere il livello della gerarchia delle risorse per il quale il membro deve disporre delle autorizzazioni.
+
Notare quanto segue:

+
** Puoi selezionare solo le cartelle e i progetti per i quali disponi delle autorizzazioni.
** Quando selezioni un'organizzazione o una cartella, concedi al membro le autorizzazioni per tutti i suoi contenuti.
** È possibile assegnare il ruolo di *Amministratore organizzazione* solo a livello di organizzazione.


. *Seleziona una categoria*, quindi seleziona un *Ruolo* che fornisca al membro le autorizzazioni per le risorse associate all'organizzazione, alla cartella o al progetto selezionato.
+
link:reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso"] .

. Per consentire l'accesso a più cartelle, progetti o ruoli, seleziona *Aggiungi ruolo*, scegli la cartella, il progetto o la categoria di ruolo e seleziona un ruolo.
. Selezionare *Aggiungi*.
+
La Console invia le istruzioni all'utente tramite e-mail.





=== Aggiungi un account di servizio

Gli account di servizio consentono di automatizzare le attività e di connettersi in modo sicuro alle API della console. Scegli un ID client e un segreto per configurazioni semplici oppure JWT (JSON Web Token) per una maggiore sicurezza in ambienti automatizzati o cloud-native. Seleziona il metodo che soddisfa i tuoi requisiti di sicurezza.

.Prima di iniziare:
Per l'autenticazione JWT, prepara la tua chiave pubblica o il tuo certificato.

.Passi
. Selezionare *Amministrazione > Identità e accesso*.
. Seleziona *Membri*.
. Seleziona *Aggiungi un membro*.
. Per *Tipo di membro*, seleziona *Account di servizio*.
. Inserisci un nome per l'account di servizio.
. Per utilizzare l'autenticazione JWT, seleziona *Usa autenticazione JWT con chiave privata* e carica la tua chiave RSA pubblica o il certificato. Ignora se utilizzi ID client e segreto.
+
Il tuo certificato X.509. Deve essere in formato PEM, CRT o CER.

+
.. Imposta le notifiche di scadenza per il tuo certificato.  Scegli tra sette giorni o 30 giorni.  Le notifiche di scadenza vengono inviate tramite e-mail e visualizzate nella Console agli utenti con il ruolo di Super amministratore o Amministratore dell'organizzazione.


. Utilizzare la sezione *Seleziona un'organizzazione, una cartella o un progetto* per scegliere il livello della gerarchia delle risorse per il quale il membro deve disporre delle autorizzazioni.
+
Notare quanto segue:

+
** Puoi selezionare solo le cartelle e i progetti per i quali disponi delle autorizzazioni.
** Selezionando un'organizzazione o una cartella, al membro vengono concesse autorizzazioni su tutti i suoi contenuti.
** È possibile assegnare il ruolo di *Amministratore organizzazione* solo a livello di organizzazione.


. Seleziona una *Categoria*, quindi seleziona un *Ruolo* che conceda al membro le autorizzazioni per le risorse nell'organizzazione, nella cartella o nel progetto selezionato.
+
link:reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso"] .

. Per consentire l'accesso a più cartelle, progetti o ruoli, seleziona *Aggiungi ruolo*, scegli la cartella, il progetto o la categoria di ruolo e seleziona un ruolo.
. Se non hai scelto di utilizzare l'autenticazione JWT, scarica o copia l'ID client e il segreto client.
+
La console mostra il segreto del client solo una volta. Copialo in modo sicuro: potrai ricrearlo in seguito se lo perdi.

. Se hai scelto l'autenticazione JWT, scarica o copia l'ID client e il pubblico JWT. La Console visualizza queste informazioni una sola volta e non consente di recuperarle in seguito.
. Selezionare *Chiudi*.




== Aggiungi un gruppo federato alla tua organizzazione

Puoi aggiungere un gruppo federato dal tuo provider di identità (IdP) alla tua organizzazione e assegnargli uno o più ruoli. I membri del gruppo federato ereditano i ruoli assegnati al gruppo nella Console.


IMPORTANT: Quando aggiungi un gruppo federato alla Console e gli assegni un ruolo, solo gli utenti che sono membri del gruppo nel tuo IdP e che si sono già registrati alla NetApp Console e a cui è stato esplicitamente assegnato un ruolo nella Console possono accedere alle risorse. NetApp consiglia di assegnare a questi utenti un ruolo di accesso minimo, come Organization viewer.

Prima di poter assegnare un ruolo a un gruppo federato, assicurati di aver soddisfatto i seguenti requisiti:

* Imposta la federazione tra il tuo IdP e la Console. link:concept-federation.html["Scopri come impostare una federazione."]
* Il gruppo deve già esistere nel tuo IdP e deve avere accesso all'app Console.


.Passi
. Selezionare *Amministrazione > Identità e accesso*.
. Seleziona *Membri*.
. Seleziona *Aggiungi un membro*.
. Per *Tipo di membro*, seleziona *Gruppo federato*.
. Seleziona la federazione di cui il gruppo è membro
. Per *Nome gruppo*, inserisci il nome esatto del gruppo nel tuo IdP.
. Utilizzare la sezione *Seleziona un'organizzazione, una cartella o un progetto* per scegliere il livello della gerarchia delle risorse per il quale il membro deve disporre delle autorizzazioni.
+
Notare quanto segue:

+
** Puoi selezionare solo le cartelle e i progetti per i quali disponi delle autorizzazioni.
** Selezionando un'organizzazione o una cartella, al membro vengono concesse autorizzazioni su tutti i suoi contenuti.
** È possibile assegnare il ruolo di *Amministratore organizzazione* solo a livello di organizzazione.


. Seleziona una *Categoria*, quindi seleziona un *Ruolo* che conceda al membro le autorizzazioni per le risorse nell'organizzazione, nella cartella o nel progetto selezionato.
+
link:reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso"] .

. Per consentire l'accesso a più cartelle, progetti o ruoli, seleziona *Aggiungi ruolo*, scegli la cartella, il progetto o la categoria di ruolo e seleziona un ruolo.




== Informazioni correlate

* link:concept-identity-and-access-management.html["Scopri di più sulla gestione dell'identità e degli accessi nella NetApp Console"]
* link:task-iam-get-started.html["Inizia con identità e accesso"]
* link:reference-iam-predefined-roles.html["Ruoli di accesso NetApp Console"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["Scopri di più sull'API per l'identità e l'accesso"^]

