---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Dopo esserti registrato alla NetApp Console, puoi accedere dalla console basata sul Web per iniziare a gestire la tua infrastruttura di dati e storage. 
---
= Accedi alla NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo esserti registrato alla NetApp Console, puoi accedere dalla console basata sul Web per iniziare a gestire la tua infrastruttura di dati e storage.

Dopo la registrazione, l'amministratore dell'organizzazione della Console deve aggiungere il tuo account utente a un'organizzazione prima che tu possa accedere a qualsiasi risorsa. Se accedi ma non vedi alcuna risorsa, contatta l'amministratore dell'organizzazione. link:task-user-settings.html#contact-admin["Contatta l'amministratore della tua organizzazione"].

.Passi
. Vai all'URL della NetApp Console. L'URL dipende dalla modalità della Console che la tua organizzazione sta utilizzando:
+
** *Modalità standard*: Apri un browser web e vai a https://console.netapp.com["NetApp Console"^].
** **Modalità limitata o modalità privata**: Apri un browser web e vai all'indirizzo IP in cui è installato l'agente Console.


. Nella pagina *Accedi*, inserisci l'indirizzo email associato al tuo accesso.
. A seconda del metodo di autenticazione associato al tuo login, ti verrà richiesto di inserire le tue credenziali.
+
** Le tue credenziali NSS ( NetApp Support Site) esistenti
** Un account NetApp Console utilizzando il tuo indirizzo email e una password
** Una connessione federata se l'amministratore ha configurato l'identità federation per la tua organizzazione



