---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'Se è la prima volta che utilizzi NetApp Console, l"assistente della console ti guiderà attraverso il processo di configurazione iniziale.  L"assistente ti aiuta ad aggiungere un account NetApp Support Site (NSS), un agente della console, un cluster e una licenza o un abbonamento, semplificando l"avvio della gestione dei tuoi dati.' 
---
= Inizia a utilizzare l'assistente NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se sei un utente alle prime armi di NetApp Console (SaaS) con il ruolo di amministratore dell'organizzazione, puoi utilizzare l'assistente della console per ricevere assistenza durante il processo di configurazione iniziale. L'assistente ti aiuta ad aggiungere un account NetApp Support Site (NSS), un agente della console, un cluster e una licenza o un abbonamento, semplificando l'avvio della gestione dei tuoi dati.



== Ruoli richiesti per accedere all'assistente della console

L'assistente della console è disponibile solo per gli utenti con ruolo di amministratore dell'organizzazione.

Per impostazione predefinita, la NetApp Console visualizza l'assistente della console nella home page per gli utenti che accedono per la prima volta e che dispongono del ruolo di amministratore dell'organizzazione. Rimane disponibile finché non si completano le attività obbligatorie di creazione di un agente Console e di aggiunta di un sistema.

Utilizzare l'assistente per completare queste attività, che forniscono la configurazione minima per l'ambiente NetApp Console :

* Aggiungi un account NetApp Support Site (NSS).
+
link:task-adding-nss-accounts.html["Scopri come aggiungere un account NSS"].

* Connettiti al tuo spazio di archiviazione distribuendo un agente Console.
+
link:task-install-agent-on-prem.html["Scopri come installare un agente Console in locale."]

* Gestire un sistema di archiviazione aggiungendo o scoprendo un cluster
* Aggiungi un abbonamento al marketplace o una licenza PAYGO.
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["Scopri come aggiungere licenze e abbonamenti"^].

* Esaminare le informazioni sui servizi dati.

