---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: La modalità di accesso alla console NetApp dipende dalla modalità di distribuzione utilizzata. 
---
= Accedi alla console NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La modalità di accesso alla console NetApp dipende dalla modalità di distribuzione utilizzata.

Verrai disconnesso automaticamente dopo 24 ore o se chiudi il browser.

link:concept-modes.html["Scopri di più sulle modalità di distribuzione della console"] .

[role="tabbed-block"]
====
.Modalità standard
--
Dopo esserti registrato alla NetApp Console, puoi accedere dalla console basata sul Web per iniziare a gestire la tua infrastruttura di dati e storage.

.Informazioni su questo compito
È possibile accedere alla console NetApp utilizzando una delle seguenti opzioni:

* Le tue credenziali NSS ( NetApp Support Site) esistenti
* Un account NetApp Console utilizzando il tuo indirizzo email e una password
* Una connessione federata
+
È possibile utilizzare l'accesso Single Sign-On per effettuare l'accesso utilizzando le credenziali della directory aziendale (identità federata). link:concept-federation.html["Scopri come impostare la federazione delle identità"] .



.Passi
. Apri un browser web e vai su https://console.netapp.com["Console NetApp"]
. Nella pagina *Accedi*, inserisci l'indirizzo email associato al tuo accesso.
. A seconda del metodo di autenticazione associato al tuo accesso, ti verrà richiesto di inserire le tue credenziali:
+
** Credenziali cloud NetApp : inserisci la tua password
** Utente federato: inserisci le credenziali della tua identità federata
** Account del sito di supporto NetApp : inserisci le credenziali del tuo sito di supporto NetApp




.Risultato
Ora hai effettuato l'accesso e puoi iniziare a utilizzare la gestione della tua infrastruttura multi-cloud ibrida.

--
.Modalità limitata
--
Quando si utilizza la Console in modalità limitata, è necessario accedere alla Console dall'interfaccia utente eseguita localmente sull'agente.

.Informazioni su questo compito
La Console supporta l'accesso con una delle seguenti opzioni quando è in modalità limitata:

* Un accesso alla console NetApp utilizzando il tuo indirizzo email e una password
* Una connessione federata
+
È possibile utilizzare l'accesso Single Sign-On per effettuare l'accesso utilizzando le credenziali della directory aziendale (identità federata). link:concept-federation.html["Scopri come utilizzare la federazione delle identità"] .



.Passi
. Aprire un browser Web e immettere l'indirizzo IP in cui è installato l'agente.
. Inserisci il tuo nome utente e la password per effettuare l'accesso.


--
====