---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: 'Disinstallare un agente Console per risolvere i problemi o per rimuoverlo definitivamente dall"host.  I passaggi da seguire dipendono dalla modalità di distribuzione utilizzata.  Dopo aver rimosso un agente Console dal tuo ambiente, puoi rimuoverlo dalla Console.' 
---
= Disinstallare e rimuovere un agente Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Disinstallare un agente Console per risolvere i problemi o per rimuoverlo definitivamente dall'host.  I passaggi da seguire dipendono dalla modalità di distribuzione utilizzata.  Dopo aver rimosso un agente Console dal tuo ambiente, puoi rimuoverlo dalla Console.



== Disinstallare l'agente quando ha connettività outbound

Se si utilizza la modalità standard o la modalità limitata (in altre parole, l'host dell'agente ha connettività in uscita), è necessario seguire i passaggi indicati di seguito per disinstallare l'agente.

.Passi
. Connettersi alla VM Linux per l'agente.
. Dall'host Linux, eseguire lo script di disinstallazione:
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ esegue lo script senza chiedere conferma.





== Disinstallare l'agente quando non ha connettività outbound

Se il tuo agente non dispone di connettività outbound (ad esempio, in modalità privata), devi rimuovere manualmente il software dell'agente dall'host.

.Fare un passo
. Connettersi alla VM Linux per l'agente della console.
. Dall'host Linux, eseguire i seguenti comandi:
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Dall'host Linux, eliminare i vecchi file immagine del container non utilizzati per liberare spazio nella directory /var per la reinstallazione.
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




== Rimuovere gli agenti della console dalla console

Se hai eliminato una VM dell'agente o hai disinstallato l'agente, dovresti rimuoverlo dall'elenco degli agenti nella Console. Dopo aver eliminato una VM dell'agente o aver disinstallato il software dell'agente, l'agente mostra lo stato *Disconnesso* nella Console.

Tenere presente quanto segue sulla rimozione di un agente Console:

* Questa azione non elimina la macchina virtuale.
* Questa azione non può essere annullata: una volta rimosso un agente della console, non è possibile aggiungerlo di nuovo.


.Passi
. Selezionare *Amministrazione > Agenti*.
. Nella pagina *Panoramica*, seleziona il menu azioni per un agente disconnesso e seleziona *Rimuovi agente*.
. Inserisci il nome dell'agente per confermare e poi seleziona *Rimuovi*.

