---
sidebar: sidebar 
permalink: task-install-connector-aws-marketplace.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: 'Per creare un agente Console da AWS Marketplace, è necessario configurare la rete, preparare le autorizzazioni AWS, esaminare i requisiti dell"istanza e quindi creare l"agente Console.' 
---
= Creare un agente della console da AWS Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare un agente Console in AWS direttamente da AWS Marketplace.  Per creare un agente Console da AWS Marketplace, è necessario configurare la rete, preparare le autorizzazioni AWS, esaminare i requisiti dell'istanza e quindi creare l'agente Console.

.Prima di iniziare
* Dovresti avere unlink:concept-connectors.html["comprensione degli agenti della console"] .
* Dovresti rivederelink:reference-limitations.html["Limitazioni dell'agente della console"] .




== Passaggio 1: configurare la rete

Assicurarsi che il percorso di rete per l'agente della console soddisfi i seguenti requisiti per gestire le risorse del cloud ibrido.

VPC e sottorete:: Quando si crea l'agente Console, è necessario specificare la VPC e la subnet in cui deve risiedere.


Connessioni alle reti di destinazione:: L'agente Console richiede una connessione di rete alla posizione in cui si prevede di creare e gestire i sistemi.  Ad esempio, la rete in cui intendi creare sistemi Cloud Volumes ONTAP o un sistema di archiviazione nel tuo ambiente locale.


Accesso a Internet in uscita:: La posizione di rete in cui si distribuisce l'agente Console deve disporre di una connessione Internet in uscita per contattare endpoint specifici.


Endpoint contattati dall'agente della console:: L'agente della console necessita di accesso a Internet in uscita per contattare i seguenti endpoint per gestire risorse e processi all'interno dell'ambiente cloud pubblico per le operazioni quotidiane.
+
--
Gli endpoint elencati di seguito sono tutti voci CNAME.

[cols="2a,1a"]
|===
| Punti finali | Scopo 


 a| 
Servizi AWS (amazonaws.com):

* Formazione delle nuvole
* Elastic Compute Cloud (EC2)
* Gestione dell'identità e degli accessi (IAM)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* Servizio di archiviazione semplice (S3)

 a| 
Per gestire le risorse AWS.  L'endpoint dipende dalla tua regione AWS. https://docs.aws.amazon.com/general/latest/gr/rande.html["Per i dettagli, fare riferimento alla documentazione AWS"^]



 a| 
\ https://mysupport.netapp.com
 a| 
Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp .



 a| 
\ https://signin.b2c.netapp.com
 a| 
Per aggiornare le credenziali del sito di supporto NetApp (NSS) o per aggiungere nuove credenziali NSS alla console NetApp .



 a| 
\ https://api.bluexp.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com \ https://console.netapp.com \ https://components.console.bluexp.netapp.com \ https://cdn.auth0.com
 a| 
Per fornire funzionalità e servizi all'interno della NetApp Console.



 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Per ottenere immagini per gli aggiornamenti dell'agente della console.

* Quando si distribuisce un nuovo agente, il controllo di convalida verifica la connettività agli endpoint correnti.  Se usilink:link:reference-networking-saas-console-previous.html["punti finali precedenti"] , il controllo di convalida fallisce.  Per evitare questo errore, saltare il controllo di convalida.
+
Sebbene gli endpoint precedenti siano ancora supportati, NetApp consiglia di aggiornare le regole del firewall agli endpoint correnti il ​​prima possibile. link:reference-networking-saas-console-previous.html#update-endpoint-list["Scopri come aggiornare l'elenco degli endpoint"] .

* Quando esegui l'aggiornamento agli endpoint correnti nel firewall, gli agenti esistenti continueranno a funzionare.


|===
--


Server proxy:: NetApp supporta sia configurazioni proxy esplicite che trasparenti.  Se si utilizza un proxy trasparente, è necessario fornire solo il certificato per il server proxy.  Se si utilizza un proxy esplicito, saranno necessari anche l'indirizzo IP e le credenziali.
+
--
* indirizzo IP
* Credenziali
* Certificato HTTPS


--


porti:: Non c'è traffico in entrata verso l'agente della console, a meno che non venga avviato dall'utente o utilizzato come proxy per inviare messaggi AutoSupport da Cloud Volumes ONTAP al supporto NetApp .
+
--
* HTTP (80) e HTTPS (443) forniscono l'accesso all'interfaccia utente locale, che utilizzerai in rare circostanze.
* SSH (22) è necessario solo se è necessario connettersi all'host per la risoluzione dei problemi.
* Le connessioni in entrata sulla porta 3128 sono necessarie se si distribuiscono sistemi Cloud Volumes ONTAP in una subnet in cui non è disponibile una connessione Internet in uscita.
+
Se i sistemi Cloud Volumes ONTAP non dispongono di una connessione Internet in uscita per inviare messaggi AutoSupport , la Console configura automaticamente tali sistemi per utilizzare un server proxy incluso nell'agente della Console.  L'unico requisito è assicurarsi che il gruppo di sicurezza dell'agente Console consenta connessioni in entrata sulla porta 3128.  Sarà necessario aprire questa porta dopo aver distribuito l'agente Console.



--


Abilita NTP:: Se si prevede di utilizzare NetApp Data Classification per analizzare le origini dati aziendali, è necessario abilitare un servizio Network Time Protocol (NTP) sia sull'agente della console sia sul sistema NetApp Data Classification, in modo che l'ora sia sincronizzata tra i sistemi. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Scopri di più sulla classificazione dei dati NetApp"^]
+
--
Implementare questo accesso alla rete dopo aver creato l'agente Console.

--




== Passaggio 2: impostare le autorizzazioni AWS

Per preparare la distribuzione di un marketplace, crea policy IAM in AWS e associale a un ruolo IAM.  Quando si crea l'agente della console da AWS Marketplace, viene richiesto di selezionare il ruolo IAM.

.Passi
. Accedi alla console AWS e vai al servizio IAM.
. Crea una policy:
+
.. Selezionare *Criteri > Crea criterio*.
.. Seleziona *JSON* e copia e incolla il contenuto dellink:reference-permissions-aws.html["Criterio IAM per l'agente della console"] .
.. Completare i passaggi rimanenti per creare la policy.
+
Potrebbe essere necessario creare una seconda policy basata sui servizi dati NetApp che si intende utilizzare.  Per le regioni standard, le autorizzazioni sono distribuite su due policy.  Sono necessarie due policy a causa del limite massimo di dimensione dei caratteri per le policy gestite in AWS. link:reference-permissions-aws.html["Scopri di più sui criteri IAM per l'agente della console"] .



. Crea un ruolo IAM:
+
.. Selezionare *Ruoli > Crea ruolo*.
.. Selezionare *Servizio AWS > EC2*.
.. Aggiungi autorizzazioni allegando la policy appena creata.
.. Completa i passaggi rimanenti per creare il ruolo.




.Risultato
Ora disponi di un ruolo IAM che puoi associare all'istanza EC2 durante la distribuzione da AWS Marketplace.



== Passaggio 3: rivedere i requisiti dell'istanza

Quando si crea l'agente Console, è necessario scegliere un tipo di istanza EC2 che soddisfi i seguenti requisiti.

processore:: 8 core o 8 vCPU
Memoria RAM:: 32 GB
Tipo di istanza AWS EC2:: Un tipo di istanza che soddisfa i requisiti di CPU e RAM sopra indicati.  Consigliamo t3.2xlarge.




== Passaggio 4: creare l'agente della console

Crea l'agente della console direttamente da AWS Marketplace.

.Informazioni su questo compito
La creazione dell'agente Console da AWS Marketplace distribuisce un'istanza EC2 in AWS utilizzando una configurazione predefinita. link:reference-connector-default-config.html["Scopri la configurazione predefinita per l'agente Console"] .

.Prima di iniziare
Dovresti avere quanto segue:

* Una VPC e una subnet che soddisfano i requisiti di rete.
* Un ruolo IAM con una policy associata che include le autorizzazioni richieste per l'agente della console.
* Autorizzazioni per iscriversi e annullare l'iscrizione ad AWS Marketplace per il tuo utente IAM.
* Una conoscenza dei requisiti di CPU e RAM per l'istanza.
* Una coppia di chiavi per l'istanza EC2.


.Passi
. Vai al https://aws.amazon.com/marketplace/pp/prodview-jbay5iyfmu6ui["Elenco degli agenti della console NetApp su AWS Marketplace"^]
. Nella pagina Marketplace, seleziona *Continua ad abbonarti*.
. Per abbonarsi al software, selezionare *Accetta i termini*.
+
Il processo di iscrizione può richiedere alcuni minuti.

. Una volta completato il processo di sottoscrizione, seleziona *Continua alla configurazione*.
. Nella pagina *Configura questo software*, assicurati di aver selezionato la regione corretta, quindi seleziona *Continua per avviare*.
. Nella pagina *Avvia questo software*, in *Scegli azione*, seleziona *Avvia tramite EC2* e poi seleziona *Avvia*.
+
Utilizzare la console EC2 per avviare l'istanza e associare un ruolo IAM.  Ciò non è possibile con l'azione *Avvia dal sito Web*.

. Seguire le istruzioni per configurare e distribuire l'istanza:
+
** *Nome e tag*: inserisci un nome e dei tag per l'istanza.
** *Immagini dell'applicazione e del sistema operativo*: saltare questa sezione.  L'AMI dell'agente Console è già selezionata.
** *Tipo di istanza*: a seconda della disponibilità regionale, scegli un tipo di istanza che soddisfi i requisiti di RAM e CPU (t3.2xlarge è preselezionato e consigliato).
** *Coppia di chiavi (accesso)*: seleziona la coppia di chiavi che desideri utilizzare per connetterti in modo sicuro all'istanza.
** *Impostazioni di rete*: modifica le impostazioni di rete secondo necessità:
+
*** Selezionare la VPC e la subnet desiderate.
*** Specificare se l'istanza deve avere un indirizzo IP pubblico.
*** Specificare le impostazioni del gruppo di sicurezza che abilitano i metodi di connessione richiesti per l'istanza dell'agente Console: SSH, HTTP e HTTPS.
+
link:reference-ports-aws.html["Visualizza le regole del gruppo di sicurezza per AWS"] .



** *Configura archiviazione*: mantieni le dimensioni e il tipo di disco predefiniti per il volume root.
+
Se si desidera abilitare la crittografia Amazon EBS sul volume root, selezionare *Avanzate*, espandere *Volume 1*, selezionare *Crittografato* e quindi scegliere una chiave KMS.

** *Dettagli avanzati*: in *Profilo istanza IAM*, seleziona il ruolo IAM che include le autorizzazioni richieste per l'agente della console.
** *Riepilogo*: rivedere il riepilogo e selezionare *Avvia istanza*.
+
AWS avvia l'agente della console con le impostazioni specificate e l'agente della console viene eseguito in circa dieci minuti.



+

NOTE: Se l'installazione non riesce, è possibile visualizzare i registri e un report per risolvere il problema.link:task-troubleshoot-connector.html#troubleshoot-installation["Scopri come risolvere i problemi di installazione."]

. Aprire un browser Web da un host che dispone di una connessione alla macchina virtuale dell'agente Console e all'URL dell'agente Console.
. Dopo aver effettuato l'accesso, configura l'agente Console:
+
.. Specificare l'organizzazione della console da associare all'agente della console.
.. Inserisci un nome per il sistema.
.. In *Stai utilizzando un ambiente protetto?* mantieni disattivata la modalità con restrizioni.
+
Per utilizzare la Console in modalità standard, disattivare la modalità limitata.  Dovresti abilitare la modalità limitata solo se disponi di un ambiente sicuro e desideri disconnettere questo account dai servizi backend della Console.  Se è così,link:task-quick-start-restricted-mode.html["segui i passaggi per iniziare a usare NetApp Console in modalità limitata"] .

.. Seleziona *Iniziamo*.




.Risultato
L'agente Console è ora installato e configurato con la tua organizzazione Console.

Apri un browser web e vai su https://console.netapp.com["Console NetApp"^] per iniziare a utilizzare l'agente Console con la Console.

Se disponi di bucket Amazon S3 nello stesso account AWS in cui hai creato l'agente della console, vedrai apparire automaticamente un ambiente di lavoro Amazon S3 nella pagina *Sistemi*. https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Scopri come gestire i bucket S3 dalla console NetApp"^]
