= Agente console 4.2.0
:allow-uri-read: 




=== Agente console 4.2.0

La versione 4.2.0 supporta sia la modalità standard che quella limitata.

Questa versione dell'agente Console include miglioramenti della sicurezza, correzioni di bug e le seguenti funzionalità:

.Supporto per Google Cloud Infrastructure Manager
NetApp ora utilizza Google Cloud Infrastructure Manager (IM) anziché Google Cloud Deployment Manager per distribuire gli agenti e gestirli in Google Cloud.  Questa modifica è stata apportata perché Google disapproveràlink:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Cloud Deployment Manager"] .

* Tutti i nuovi agenti 4.2.0 e versioni successive utilizzano Infrastructure Manager e dovresti aggiornare sia le autorizzazioni dell'account utente che quelle dell'account di servizio utilizzate per la distribuzione.link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Visualizza il registro delle modifiche delle autorizzazioni."^]
* Quando si distribuisce un agente, il sistema crea anche un bucket Google Cloud per archiviare i file di distribuzione.


.Controlli di configurazione migliorati per gli agenti della console
* L'agente Console ora verifica la presenza di endpoint obsoleti durante l'esecuzione di un controllo della configurazione.  Se non è stato effettuato l'aggiornamento al nuovo elenco di endpoint per la versione 4.0.0 o successiva, le installazioni riescono se il sistema riesce a raggiungere l'elenco di endpoint precedente.link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Scopri di più sugli endpoint richiesti per gli agenti della console."^]
* Eseguire controlli di configurazione sugli agenti della console installati dalla console o dalla console di manutenzione dell'agente per verificare la connettività e risolvere i problemi.link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Scopri come eseguire controlli di configurazione sugli agenti della console."^]


.Scarica direttamente il software dell'agente dalla NetApp Console
Quando è necessario installare manualmente un agente, è possibile accedere al software dell'agente direttamente dalla NetApp Console , oltre che dal sito di supporto NetApp .link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Scopri come scaricare il software dell'agente Console direttamente dalla NetApp Console."^]



=== Amministrazione NetApp Console

Questa versione include quanto segue:

.Possibilità di impostare notifiche per le credenziali in scadenza
Imposta notifiche per la scadenza delle credenziali sugli account di servizio e sulle federazioni.  Scegli tra sette o 30 giorni.  La Console visualizza notifiche e invia e-mail agli utenti con il ruolo appropriato.  Gli amministratori dell'organizzazione ricevono notifiche sugli account di servizio.  Gli amministratori dell'organizzazione, gli amministratori della federazione e i visualizzatori della federazione ricevono notifiche sulla federazione.

.Gli accessi locali non sono disponibili dopo aver abilitato la federazione
Dopo aver attivato la federazione per un'organizzazione Console, gli utenti non possono utilizzare gli accessi locali e vengono indirizzati agli accessi federati.

.Miglioramenti dell'usabilità per le pagine di gestione dell'archiviazione
Le informazioni dettagliate sui sistemi ONTAP on-premise (e FSx per ONTAP) sono ora più facili da visualizzare e gestire dalle pagine di gestione dell'archiviazione.

* La pagina * Discoverable systems* separa le informazioni riepilogative dalla visualizzazione a schede dei sistemi disponibili, semplificando la visualizzazione di informazioni complete sui sistemi rilevabili.

