= Console agent 4.6.0
:allow-uri-read: 




[[console-agent-4-6-0]]
=== Console agent 4.6.0

La versione 4.6.0 supporta sia la modalità standard che la modalità limitata.

Questa versione dell'agente Console include miglioramenti della sicurezza e correzioni di bug, oltre alla seguente nuova funzionalità.

.Supporto per i controlli di configurazione dello spazio su disco
È possibile verificare che lo spazio su disco necessario per l'agente della Console sia disponibile utilizzando i controlli di configurazione. È possibile eseguire i controlli di configurazione dalla Console o dalla console di manutenzione dell'agente. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["Scopri di più sull'esecuzione dei controlli di configurazione sull'agente della console"^]

.Aggiornare un agente Console distribuito da vCenter utilizzando un ISO
Se hai distribuito un agente Console in vCenter utilizzando un file OVA, ora puoi aggiornarlo a una nuova versione montando un'immagine ISO sulla macchina virtuale ed eseguendo l'aggiornamento dalla console di manutenzione della macchina virtuale. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Scopri come aggiornare un agente Console distribuito da vCenter"^]
