= 
:allow-uri-read: 


Dopo aver installato e configurato l'agente Console, aggiungi le tue credenziali cloud in modo che l'agente Console disponga delle autorizzazioni necessarie per eseguire azioni in AWS o Azure.

[role="tabbed-block"]
====
.AWS
--
.Prima di iniziare
Se hai appena creato queste credenziali AWS, potrebbero volerci alcuni minuti prima che siano disponibili.  Attendi qualche minuto prima di aggiungere le credenziali alla Console.

.Passi
. Selezionare *Amministrazione > Credenziali*.
. Selezionare *Credenziali dell'organizzazione*.
. Selezionare *Aggiungi credenziali* e seguire i passaggi della procedura guidata.
+
.. *Posizione delle credenziali*: seleziona *Amazon Web Services > Agente.
.. *Definisci credenziali*: inserisci una chiave di accesso AWS e una chiave segreta.
.. *Abbonamento Marketplace*: associa un abbonamento Marketplace a queste credenziali abbonandoti ora o selezionando un abbonamento esistente.
.. *Revisione*: conferma i dettagli sulle nuove credenziali e seleziona *Aggiungi*.




Ora puoi andare al https://console.netapp.com["NetApp Console"^] per iniziare a utilizzare l'agente Console.

--
.Azzurro
--
.Prima di iniziare
Se hai appena creato queste credenziali di Azure, potrebbero volerci alcuni minuti prima che siano disponibili.  Attendi qualche minuto prima di aggiungere le credenziali all'agente della console.

.Passi
. Selezionare *Amministrazione > Credenziali*.
. Selezionare *Aggiungi credenziali* e seguire i passaggi della procedura guidata.
+
.. *Posizione delle credenziali*: selezionare *Microsoft Azure > Agente*.
.. *Definisci credenziali*: immetti le informazioni sull'entità servizio Microsoft Entra che concede le autorizzazioni richieste:
+
*** ID applicazione (client)
*** ID directory (tenant)
*** Segreto del cliente


.. *Abbonamento Marketplace*: associa un abbonamento Marketplace a queste credenziali abbonandoti ora o selezionando un abbonamento esistente.
.. *Revisione*: conferma i dettagli sulle nuove credenziali e seleziona *Aggiungi*.




.Risultato
L'agente della console ora dispone delle autorizzazioni necessarie per eseguire azioni in Azure per tuo conto.  Ora puoi andare al https://console.netapp.com["NetApp Console"^] per iniziare a utilizzare l'agente Console.

--
====