= 
:allow-uri-read: 


. Rivedi le tue selezioni per verificare che la configurazione sia corretta.
+
.. La check box *Convalida configurazione agente* è selezionata per impostazione predefinita per consentire alla Console di convalidare i requisiti di connettività di rete durante la distribuzione. Se la Console non riesce a distribuire l'agente, fornisce un report per aiutarti nella risoluzione dei problemi. Se la distribuzione ha esito positivo, non viene fornito alcun report.


+
[NOTE]
====
** Se si utilizza ancora la link:reference-networking-saas-console-previous.html["punti finali precedenti"] utilizzata per gli aggiornamenti dell'agente, la convalida fallisce con un errore. Per evitarlo, deselezionare la check box per saltare il controllo di convalida.
** Durante l'installazione, NetApp verifica che l'host dell'agente disponga di almeno l'80% dello spazio su disco totale disponibile, che include 48 GB in `/opt` e 32 GB in `/var` (80 GB totali). Dopo l'installazione, è necessario che rimanga disponibile almeno il 20% dello spazio su disco totale, che include 12 GB in `/opt` e 8 GB in `/var` (20 GB totali).


====

