= 
:allow-uri-read: 


Crea un ruolo e applicalo a un account di servizio che utilizzerai per l'istanza della VM dell'agente Console.

.Passi
. Crea un ruolo personalizzato in Google Cloud:
+
.. Creare un file YAML che includa le autorizzazioni definite inlink:reference-permissions-gcp.html["Criterio dell'agente della console per Google Cloud"] .
.. Da Google Cloud, attiva Cloud Shell.
.. Carica il file YAML che include le autorizzazioni richieste per l'agente della console.
.. Crea un ruolo personalizzato utilizzando `gcloud iam roles create` comando.
+
L'esempio seguente crea un ruolo denominato "connettore" a livello di progetto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentazione di Google Cloud: creazione e gestione di ruoli personalizzati"^]



. Crea un account di servizio in Google Cloud:
+
.. Dal servizio IAM e amministrazione, seleziona *Account di servizio > Crea account di servizio*.
.. Inserisci i dettagli dell'account di servizio e seleziona *Crea e continua*.
.. Seleziona il ruolo che hai appena creato.
.. Completa i passaggi rimanenti per creare il ruolo.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentazione di Google Cloud: creazione di un account di servizio"^]





.Risultato
Ora disponi di un account di servizio che puoi assegnare all'istanza VM dell'agente Console.
