= 
:allow-uri-read: 


.Prima di iniziare
Dovresti avere quanto segue:

* Privilegi di root per installare l'agente Console.
* Dettagli su un server proxy, se è necessario un proxy per l'accesso a Internet dall'agente della console.
+
Dopo l'installazione è possibile configurare un server proxy, ma per farlo è necessario riavviare l'agente della console.

* Un certificato firmato da una CA, se il server proxy utilizza HTTPS o se il proxy è un proxy di intercettazione.



NOTE: Non è possibile impostare un certificato per un server proxy trasparente durante l'installazione manuale dell'agente Console. Se è necessario impostare un certificato per un server proxy trasparente, è necessario utilizzare la Console di manutenzione dopo l'installazione. Scopri di più sulink:reference-agent-maint-console-proxy.html["Console di manutenzione dell'agente"] .

.Informazioni su questo compito
Dopo l'installazione, l'agente Console si aggiorna automaticamente se è disponibile una nuova versione.

.Passi
. Se le variabili di sistema _http_proxy_ o _https_proxy_ sono impostate sull'host, rimuoverle:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se non si rimuovono queste variabili di sistema, l'installazione fallirà.

. Scaricare il software dell'agente Console e copiarlo sull'host Linux.  È possibile scaricarlo dalla NetApp Console o dal sito di supporto NetApp .
+
** NetApp Console: vai su *Agenti > Gestione > Distribuisci agente > On-prem > Installazione manuale*.
+
Scegli di scaricare i file di installazione dell'agente o un URL ai file.



+

NOTE: Scarica il programma di installazione dell'agente "online" pensato per l'utilizzo nella tua rete o nel cloud. È disponibile un programma di installazione "offline" separato per l'agente Console, ma è supportato solo con distribuzioni in modalità privata.

+
** Sito di supporto NetApp (necessario se non si ha già accesso alla console) https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["Sito di supporto NetApp"^] ,


. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Dove <versione> è la versione dell'agente Console scaricato.

. Se si esegue l'installazione in un ambiente Government Cloud, disattivare i controlli di configurazione.link:task-troubleshoot-agent.html#disable-config-check["Scopri come disattivare i controlli di configurazione per le installazioni manuali."]
. Eseguire lo script di installazione.
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Sarà necessario aggiungere le informazioni sul proxy se la rete richiede un proxy per l'accesso a Internet. È possibile aggiungere un proxy esplicito durante l'installazione. I parametri  `--proxy` e  `--cacert` sono facoltativi e non verrà richiesto di aggiungerli. Se si dispone di un proxy server esplicito, sarà necessario immettere i parametri come mostrato.




NOTE: Se vuoi configurare un proxy trasparente, puoi farlo dopo l'installazione. link:reference-agent-maint-console-proxy.html["Scopri di più sulla console di manutenzione dell'agente"]

+

Ecco un esempio di configurazione di un server proxy esplicito con un certificato firmato da una CA:

+

[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` configura l'agente Console per utilizzare un proxy server utilizzando uno dei seguenti formati:

+ * \http://address:port * \http://user-name:password@address:port * \http://domain-name%92user-name:password@address:port * \https://address:port * \https://user-name:password@address:port * \https://domain-name%92user-name:password@address:port

+ Nota quanto segue:

+ ** L'utente può essere un utente locale o un utente di dominio. ** Per un utente di dominio, è necessario utilizzare il codice ASCII per una \ come mostrato sopra. ** L'agente Console non supporta nomi utente o password che includono il carattere @. ** Se la password include uno dei seguenti caratteri speciali, è necessario eseguire l'escape di quel carattere speciale anteponendo una barra rovesciata: & o !

+ Ad esempio:

+ \http://bxpproxyuser:netapp1\!@address:3128

. Se hai utilizzato Podman, dovrai modificare la porta aardvark-dns.
+
.. Eseguire l'SSH sulla macchina virtuale dell'agente Console.
.. Aprire il file podman _/usr/share/containers/containers.conf_ e modificare la porta scelta per il servizio DNS Aardvark.  Ad esempio, cambialo in 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
Per esempio:

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. Riavviare la macchina virtuale dell'agente Console.




. Attendi il completamento dell'installazione.
+
Al termine dell'installazione, il servizio agente della console (occm) viene riavviato due volte se è stato specificato un server proxy.




NOTE: Se l'installazione non riesce, puoi visualizzare il report e i registri di installazione per aiutarti a risolvere i problemi.link:task-troubleshoot-agent.html#troubleshoot-installation["Scopri come risolvere i problemi di installazione."]

. Aprire un browser Web da un host che dispone di una connessione alla macchina virtuale dell'agente Console e immettere il seguente URL:
+
https://_ipaddress_[]

. Dopo aver effettuato l'accesso, configura l'agente Console:
+
.. Specificare l'organizzazione da associare all'agente Console.
.. Inserisci un nome per il sistema.
.. In *Stai utilizzando un ambiente protetto?* mantieni disattivata la modalità con restrizioni.
+
È consigliabile disattivare la modalità limitata perché questi passaggi descrivono come utilizzare la Console in modalità standard.  Dovresti abilitare la modalità limitata solo se disponi di un ambiente sicuro e desideri disconnettere questo account dai servizi backend.  Se è così,link:task-quick-start-restricted-mode.html["segui i passaggi per iniziare a utilizzare la NetApp Console in modalità limitata"] .

.. Seleziona *Iniziamo*.



