= Porta da utilizzare per il demone di inoltro DNS con Netavark nel bridge rootful
:allow-uri-read: 


.Prima di iniziare
Dovresti avere quanto segue:

* Privilegi di root per installare l'agente Console.
* Dettagli su un server proxy, se è necessario un proxy per l'accesso a Internet dall'agente della console.
+
Dopo l'installazione è possibile configurare un server proxy, ma per farlo è necessario riavviare l'agente della console.

* Un certificato firmato da una CA, se il server proxy utilizza HTTPS o se il proxy è un proxy di intercettazione.



NOTE: Non è possibile impostare un certificato per un server proxy trasparente durante l'installazione manuale dell'agente Console. Se è necessario impostare un certificato per un server proxy trasparente, è necessario utilizzare la Console di manutenzione dopo l'installazione. Scopri di più sulink:reference-connector-maint-console.html["Console di manutenzione dell'agente"] .

.Informazioni su questo compito
Il programma di installazione disponibile sul sito di supporto NetApp potrebbe essere una versione precedente.  Dopo l'installazione, l'agente Console si aggiorna automaticamente se è disponibile una nuova versione.

.Passi
. Se le variabili di sistema _http_proxy_ o _https_proxy_ sono impostate sull'host, rimuoverle:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se non si rimuovono queste variabili di sistema, l'installazione non riuscirà.

. Scarica il software dell'agente Console da https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sito di supporto NetApp"^] e quindi copiarlo sull'host Linux.
+
Dovresti scaricare il programma di installazione dell'agente "online" pensato per l'uso nella tua rete o nel cloud.

. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Dove <versione> è la versione dell'agente Console scaricato.

. Eseguire lo script di installazione.
+
[source, cli]
----
./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>

+
You'll need to add proxy information if your network requires a proxy for internet access. You can add either a transparent or explicit proxy. The --proxy and --cacert parameters are optional and you won't be prompted to add them. If you have a proxy server, you will need to enter the parameters as shown.
+
Here is an example configuring an explicit proxy server with a CA-signed certificate:
+
[source,cli]
----


[listing]
----
+
--proxy configures the Console agent to use an HTTP or HTTPS proxy server using one of the following formats:
+
* \http://address:port
* \http://user-name:password@address:port
* \http://domain-name%92user-name:password@address:port
* \https://address:port
* \https://user-name:password@address:port
* \https://domain-name%92user-name:password@address:port
+
Note the following:
+
** The user can be a local user or domain user.
** For a domain user, you must use the ASCII code for a \ as shown above.
** The Console agent doesn't support user names or passwords that include the @ character.
** If the password includes any of the following special characters, you must escape that special character by prepending it with a backslash: & or !
+
For example:
+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert specifies a CA-signed certificate to use for HTTPS access between Console agent and the proxy server. This parameter is required for HTTPS proxy servers, intercepting proxy servers, and transparent proxy servers.

+
Here is an example configuring a transparent proxy server. When you configure a transparent proxy, you don't need to define the proxy server. You only add a CA-signed certificate to your Console agent host:

+
[source,cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
[listing]
----
. If you used Podman, you'll need to adjust the aardvark-dns port.
.. SSH to the Console agent virtual machine.
.. Open podman _/usr/share/containers/containers.conf_ file and modify the chosen port for Aardvark DNS service. For example, change it to 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf

[listing]
----
+
For example:
+
[source,text]
----


= Porta da utilizzare per il demone di inoltro DNS con Netavark nel bridge rootful



= modalità e DNS abilitati.



= L'utilizzo di una porta alternativa potrebbe essere utile se altri servizi DNS dovessero



= eseguito sulla macchina.

# dns_bind_port = 54

[listing]
----
.. Reboot the Console agent virtual machine.
//end::main-steps[]

//tag::standard-mode-steps-for-cloud[]
. Wait for the installation to complete.
+
At the end of the installation, the Console agent service (occm) restarts twice if you specified a proxy server.

. Open a web browser from a host that has a connection to the Console agent virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Console agent:
.. Specify the organization to associate with the Console agent.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use the Console in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with the NetApp Console in restricted mode].
.. Select *Let's start*.

//end::standard-mode-steps-for-cloud[]
----